# This file was auto-generated by Fern from our API Definition.

import typing

from ... import core
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.watermark_detection_response import WatermarkDetectionResponse
from .raw_client import AsyncRawWatermarkClient, RawWatermarkClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WatermarkClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWatermarkClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWatermarkClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWatermarkClient
        """
        return self._raw_client

    def detect(
        self, *, audio: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> WatermarkDetectionResponse:
        """
        Check whether a clip carries the watermark Speechify seals into audio it
        generates. Upload the audio as `audio`; nothing about it is stored, and
        no voice is read or written.

        Read the answer carefully in one direction. A `watermarked: true` is
        positive evidence that the audio came from Speechify synthesis. A
        `watermarked: false` is NOT proof that it did not: only models
        redeployed since the watermark shipped mark their output, the detector
        needs at least three seconds of clear speech to judge, and re-encoding
        or changing the speed of a clip degrades the mark. Treat a negative as
        the absence of evidence rather than as evidence of absence.

        Checks are rate-limited well below the synthesis budget: this is a
        forensic question, not a data-plane call.

        Parameters
        ----------
        audio : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WatermarkDetectionResponse
            The clip was checked.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-27",
            token="YOUR_TOKEN",
        )
        client.audio.watermark.detect()
        """
        _response = self._raw_client.detect(audio=audio, request_options=request_options)
        return _response.data


class AsyncWatermarkClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWatermarkClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWatermarkClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWatermarkClient
        """
        return self._raw_client

    async def detect(
        self, *, audio: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> WatermarkDetectionResponse:
        """
        Check whether a clip carries the watermark Speechify seals into audio it
        generates. Upload the audio as `audio`; nothing about it is stored, and
        no voice is read or written.

        Read the answer carefully in one direction. A `watermarked: true` is
        positive evidence that the audio came from Speechify synthesis. A
        `watermarked: false` is NOT proof that it did not: only models
        redeployed since the watermark shipped mark their output, the detector
        needs at least three seconds of clear speech to judge, and re-encoding
        or changing the speed of a clip degrades the mark. Treat a negative as
        the absence of evidence rather than as evidence of absence.

        Checks are rate-limited well below the synthesis budget: this is a
        forensic question, not a data-plane call.

        Parameters
        ----------
        audio : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WatermarkDetectionResponse
            The clip was checked.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-27",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.audio.watermark.detect()


        asyncio.run(main())
        """
        _response = await self._raw_client.detect(audio=audio, request_options=request_options)
        return _response.data
