# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.hosted_api_mount import HostedApiMount
from ...types.hosted_api_resolver import HostedApiResolver
from ...types.hosted_api_route import HostedApiRoute
from ...types.list_hosted_api_routes_response import ListHostedApiRoutesResponse
from .raw_client import AsyncRawRoutesClient, RawRoutesClient
from .types.create_hosted_api_route_request_method import CreateHostedApiRouteRequestMethod
from .types.update_hosted_api_route_request_method import UpdateHostedApiRouteRequestMethod

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RoutesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRoutesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRoutesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRoutesClient
        """
        return self._raw_client

    def list_routes(
        self,
        api_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[HostedApiRoute, ListHostedApiRoutesResponse]:
        """
        List a hosted API's routes in creation order.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[HostedApiRoute, ListHostedApiRoutesResponse]
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        response = client.hosted_apis.routes.list_routes(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_routes(api_id, cursor=cursor, limit=limit, request_options=request_options)

    def create_route(
        self,
        api_id: str,
        *,
        method: CreateHostedApiRouteRequestMethod,
        path: str,
        resolver: HostedApiResolver,
        idempotency_key: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        response_schema: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        cache_ttl_seconds: typing.Optional[int] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApiRoute:
        """
        Add a route: a method + path answered by a resolver. `store_query`,
        `store_document` and `store_aggregate` serve a store; `store_write`
        lands the POST body as a document (`write_mode` create / replace /
        merge; POST only, never on a public API, counted against
        `daily_write_cap`, deduplicated on `Idempotency-Key`); `run_latest`
        serves the newest structured output of a schedule trigger's runs;
        `run` starts a run through a webhook trigger per request (POST only,
        never on a public API) and waits up to `wait_seconds` before answering
        202 with a handle to poll at `/_runs/{run_id}`; `file` serves one
        published file, or a whole published tree when the path ends in `*`
        (`/app/*` with `file_root` and `file_index`); `tool` calls one read
        operation of an `openapi` tool definition, or one tool of an `mcp`
        tool definition's server, in the API's project whose `approval` is
        null or `auto` (POST only, never on a public API, counted against
        `daily_read_cap`): the consumer's JSON body is the arguments and the
        connector's answer, after the tool's response mapping, is the
        response. An `mcp` route pins the tool's input schema as
        `resolver.input_schema` when it is written.
        Where-clause values and
        the document id may be `{{query.x}}`, `{{path.x}}` or `{{body.x}}`
        templates bound from the consumer's request, or `{{user.x}}` claims of
        the verified caller on a `user_token`, `workspace` or `owner` API; a
        clause whose template is absent is skipped. On those three modes a
        written document is stamped `user_identity` as the caller and only
        they can replace or merge it. Two bindings are refused at write time:
        `{{user.*}}` on an API that names no caller, and a clause on
        `user_identity` bound from a request template, which would let any
        caller read any user's rows.

        On an API with `mcp_enabled`, every enabled route except a `file`
        route is also an MCP tool. The tool's name comes from the route's
        `name`: every run of characters outside letters, digits, `_` and `-`
        becomes `_`, leading and trailing `_` are dropped, and the result is
        cut to 64 characters. A route with no name is listed under a name
        built from its method and path (`post_issues_open`), and a name two
        routes would share takes `_2`, `_3` in route order, so read the names
        from the face's `tools/list` rather than deriving them. The route's
        `description` is what the client's model reads to choose the tool,
        falling back to the operation's summary on a `tool` route. Name and
        describe a route for that reader.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        method : CreateHostedApiRouteRequestMethod

        path : str
            Lowercase segments of letters, digits, `. _ -` or a `{param}`; `/openapi.json`, `/_runs` and `/mcp` are reserved.

        resolver : HostedApiResolver

        idempotency_key : typing.Optional[str]
            A client-generated key (an opaque string, max 255 chars) that makes a
            side-effect POST safe to retry: the server runs the operation exactly
            once and replays the first response (its status and body) for 24 hours.
            Reusing a key with a different request body, or while the first request
            is still in flight, returns `409 idempotency_conflict`. A replayed
            response carries the `Idempotent-Replayed: true` header.

        name : typing.Optional[str]
            The route's name, 1-128 letters, digits, spaces, `.`, `_` or `-`.
            On an API with `mcp_enabled` the MCP tool's name comes from it:
            each run of other characters (a space included) becomes `_`,
            leading and trailing `_` are dropped, and the result is cut to 64
            characters. A route with no name is listed under a name built from
            its method and path, and a name two routes would share takes `_2`,
            `_3` in route order; the face's `tools/list` is the authority. Pick
            a verb-first name a model can choose by.

        description : typing.Optional[str]
            What the route does. On an API with `mcp_enabled` it is the MCP
            tool description a client's model reads to choose the tool, so say
            what it returns and when to call it; a `tool` route with none falls
            back to the operation's summary.

        response_schema : typing.Optional[typing.Dict[str, typing.Any]]

        cache_ttl_seconds : typing.Optional[int]

        enabled : typing.Optional[bool]
            Enabled when omitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiRoute
            The created route.

        Examples
        --------
        from speechify import HostedApiResolver, HostedApiResolverOrderBy, Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.routes.create_route(
            api_id="api_01kc4q3r9s6t8v0w2x4y6z8a0b",
            method="GET",
            path="/leads",
            name="list_leads",
            description="List leads, highest value first.",
            resolver=HostedApiResolver(
                type="store_query",
                store_id="store_01kc4q5t1v3w5x7y9z1a3b5c7d",
                collection="leads",
                order_by=HostedApiResolverOrderBy(
                    field="value",
                    direction="desc",
                ),
            ),
            cache_ttl_seconds=30,
        )
        """
        _response = self._raw_client.create_route(
            api_id,
            method=method,
            path=path,
            resolver=resolver,
            idempotency_key=idempotency_key,
            name=name,
            description=description,
            response_schema=response_schema,
            cache_ttl_seconds=cache_ttl_seconds,
            enabled=enabled,
            request_options=request_options,
        )
        return _response.data

    def mount_routes(
        self,
        api_id: str,
        *,
        tool_id: str,
        idempotency_key: typing.Optional[str] = None,
        operations: typing.Optional[typing.Sequence[str]] = OMIT,
        name_prefix: typing.Optional[str] = OMIT,
        path_prefix: typing.Optional[str] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        include_writes: typing.Optional[bool] = OMIT,
        plan_digest: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApiMount:
        """
        Publish a connector's operations onto the API in one call: one `tool`
        route per operation of an `openapi` tool definition, or per tool its
        `mcp` server lists, named `<name_prefix>__<operation>` at
        `<path_prefix>/<operation>`, so two connectors' tools stay apart on
        the MCP face and inside its 64-character tool names.

        Send `dry_run: true` first. The answer lists every operation with
        its effective `action_class` and `approval`, whether a route can serve
        it, and the `action` a mount takes: `create`, `update` (an MCP tool
        whose input schema changed since its route was written; `changes`
        names what), `unchanged`, `skip` (with the `reason`: not selected, not
        a read, not auto-approved, a name or path already taken, or the route
        cap) or `stale` (a route whose operation the connector no longer
        offers, or can no longer serve; it is reported and never deleted,
        since a consumer may still call it). The same call without `dry_run`
        writes every create and update in one transaction and returns the
        written `route` on each.

        Every answer carries a `plan_digest`. Send the preview's digest with
        the apply: the apply plans again inside its transaction and writes
        only when that plan still has the digest, so a tool the server changed
        or a route edited after you reviewed is never written unseen. When it
        differs the apply writes nothing and answers 409 `mount_plan_changed`
        with the current plan, as a dry run answers it, in
        `error.details.plan`; review that and apply again with its digest,
        under a new `Idempotency-Key` if you sent one, since a key replays its
        first answer, this 409 included. The digest covers every operation the
        connector offers and every route the API holds for it whatever
        `operations` selects, so a preview of everything and an apply of a
        selection share one. An apply without it writes whatever the mount
        plans at that moment.

        Mounting again is the refresh. Every route the API holds for the
        connector is compared with what it offers now, whatever its name,
        path or the selection, so an upstream change is seen as a diff before
        anyone's client sees it. `operations` selects what to create; omit it
        to create a route for every operation a route can serve. A route an
        owner renamed or moved keeps its name and path on refresh.

        The route write's rules apply to every operation: the connector must
        be in the API's project (409 `cross_project_reference`), an MCP server
        must be reachable with its credential to be listed (400
        `validation_failed` on `tool_id` with the server's reason), and a
        public API mounts nothing. An API holds at most 200 routes; a mount
        that would pass the cap skips what does not fit. Without a
        `plan_digest`, a route changed while the mount was being planned
        answers 409 `api_route_conflict`; mount again.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        tool_id : str
            The `openapi` or `mcp` tool definition to mount, in the API's project.

        idempotency_key : typing.Optional[str]
            A client-generated key (an opaque string, max 255 chars) that makes a
            side-effect POST safe to retry: the server runs the operation exactly
            once and replays the first response (its status and body) for 24 hours.
            Reusing a key with a different request body, or while the first request
            is still in flight, returns `409 idempotency_conflict`. A replayed
            response carries the `Idempotent-Replayed: true` header.

        operations : typing.Optional[typing.Sequence[str]]
            The operations to create routes for: openapi operation ids or the
            MCP server's tool names. Omit to create a route for every operation
            a route can serve. Naming one the connector does not offer is 400
            `validation_failed` on `operations[i]`. Existing routes are compared
            whatever the selection.

        name_prefix : typing.Optional[str]
            Prefix of each created route's name, `<name_prefix>__<operation>`. Defaults to the tool's name with other characters as `_`.

        path_prefix : typing.Optional[str]
            Path each created route sits under, `<path_prefix>/<operation>`; lowercase segments of letters, digits, `.`, `_` or `-`, with no `{param}` or `*`, and not under `/mcp`, `/openapi.json` or `/_runs`. Defaults to `/<name_prefix>` in lowercase.

        dry_run : typing.Optional[bool]
            Answer what the mount would do and write nothing.

        include_writes : typing.Optional[bool]
            Create routes for operations that are not reads too, each with
            `allow_write: true`. Only an API whose `auth_mode` names a person
            takes them; the operation's `approval` must still be `auto`.
            Without it a write is a `skip` that says so.

        plan_digest : typing.Optional[str]
            The `plan_digest` of the preview you reviewed. The apply writes
            only while the plan it computes inside its transaction still has
            this digest, and otherwise writes nothing and answers 409
            `mount_plan_changed` with the current plan. Omit it to apply what
            the mount plans now. Refused with `dry_run`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiMount
            What the mount did, or on a dry run would do.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.routes.mount_routes(
            api_id="api_01kc4q3r9s6t8v0w2x4y6z8a0b",
            tool_id="tool_01kc4n9s3v7w0y4a6c8e2g4j6m",
            name_prefix="linear",
            dry_run=True,
        )
        """
        _response = self._raw_client.mount_routes(
            api_id,
            tool_id=tool_id,
            idempotency_key=idempotency_key,
            operations=operations,
            name_prefix=name_prefix,
            path_prefix=path_prefix,
            dry_run=dry_run,
            include_writes=include_writes,
            plan_digest=plan_digest,
            request_options=request_options,
        )
        return _response.data

    def get_route(
        self, api_id: str, route_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HostedApiRoute:
        """
        Retrieve one route.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        route_id : str
            Route id (prefixed external id, `route_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiRoute
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.routes.get_route(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            route_id="route_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.get_route(api_id, route_id, request_options=request_options)
        return _response.data

    def delete_route(
        self, api_id: str, route_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete a route.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        route_id : str
            Route id (prefixed external id, `route_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.routes.delete_route(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            route_id="route_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.delete_route(api_id, route_id, request_options=request_options)
        return _response.data

    def update_route(
        self,
        api_id: str,
        route_id: str,
        *,
        method: typing.Optional[UpdateHostedApiRouteRequestMethod] = OMIT,
        path: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        resolver: typing.Optional[HostedApiResolver] = OMIT,
        response_schema: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        cache_ttl_seconds: typing.Optional[int] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApiRoute:
        """
        Update a route (merge-patch); a changed method or resolver is re-validated.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        route_id : str
            Route id (prefixed external id, `route_...`).

        method : typing.Optional[UpdateHostedApiRouteRequestMethod]

        path : typing.Optional[str]

        name : typing.Optional[str]
            The route's name, 1-128 letters, digits, spaces, `.`, `_` or `-`.
            On an API with `mcp_enabled` the MCP tool's name comes from it:
            each run of other characters (a space included) becomes `_`,
            leading and trailing `_` are dropped, and the result is cut to 64
            characters. A route with no name is listed under a name built from
            its method and path, and a name two routes would share takes `_2`,
            `_3` in route order; the face's `tools/list` is the authority. Pick
            a verb-first name a model can choose by.

        description : typing.Optional[str]
            What the route does. On an API with `mcp_enabled` it is the MCP
            tool description a client's model reads to choose the tool, so say
            what it returns and when to call it; a `tool` route with none falls
            back to the operation's summary.

        resolver : typing.Optional[HostedApiResolver]

        response_schema : typing.Optional[typing.Dict[str, typing.Any]]

        cache_ttl_seconds : typing.Optional[int]

        enabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiRoute
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.routes.update_route(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            route_id="route_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.update_route(
            api_id,
            route_id,
            method=method,
            path=path,
            name=name,
            description=description,
            resolver=resolver,
            response_schema=response_schema,
            cache_ttl_seconds=cache_ttl_seconds,
            enabled=enabled,
            request_options=request_options,
        )
        return _response.data


class AsyncRoutesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRoutesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRoutesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRoutesClient
        """
        return self._raw_client

    async def list_routes(
        self,
        api_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[HostedApiRoute, ListHostedApiRoutesResponse]:
        """
        List a hosted API's routes in creation order.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[HostedApiRoute, ListHostedApiRoutesResponse]
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.hosted_apis.routes.list_routes(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_routes(api_id, cursor=cursor, limit=limit, request_options=request_options)

    async def create_route(
        self,
        api_id: str,
        *,
        method: CreateHostedApiRouteRequestMethod,
        path: str,
        resolver: HostedApiResolver,
        idempotency_key: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        response_schema: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        cache_ttl_seconds: typing.Optional[int] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApiRoute:
        """
        Add a route: a method + path answered by a resolver. `store_query`,
        `store_document` and `store_aggregate` serve a store; `store_write`
        lands the POST body as a document (`write_mode` create / replace /
        merge; POST only, never on a public API, counted against
        `daily_write_cap`, deduplicated on `Idempotency-Key`); `run_latest`
        serves the newest structured output of a schedule trigger's runs;
        `run` starts a run through a webhook trigger per request (POST only,
        never on a public API) and waits up to `wait_seconds` before answering
        202 with a handle to poll at `/_runs/{run_id}`; `file` serves one
        published file, or a whole published tree when the path ends in `*`
        (`/app/*` with `file_root` and `file_index`); `tool` calls one read
        operation of an `openapi` tool definition, or one tool of an `mcp`
        tool definition's server, in the API's project whose `approval` is
        null or `auto` (POST only, never on a public API, counted against
        `daily_read_cap`): the consumer's JSON body is the arguments and the
        connector's answer, after the tool's response mapping, is the
        response. An `mcp` route pins the tool's input schema as
        `resolver.input_schema` when it is written.
        Where-clause values and
        the document id may be `{{query.x}}`, `{{path.x}}` or `{{body.x}}`
        templates bound from the consumer's request, or `{{user.x}}` claims of
        the verified caller on a `user_token`, `workspace` or `owner` API; a
        clause whose template is absent is skipped. On those three modes a
        written document is stamped `user_identity` as the caller and only
        they can replace or merge it. Two bindings are refused at write time:
        `{{user.*}}` on an API that names no caller, and a clause on
        `user_identity` bound from a request template, which would let any
        caller read any user's rows.

        On an API with `mcp_enabled`, every enabled route except a `file`
        route is also an MCP tool. The tool's name comes from the route's
        `name`: every run of characters outside letters, digits, `_` and `-`
        becomes `_`, leading and trailing `_` are dropped, and the result is
        cut to 64 characters. A route with no name is listed under a name
        built from its method and path (`post_issues_open`), and a name two
        routes would share takes `_2`, `_3` in route order, so read the names
        from the face's `tools/list` rather than deriving them. The route's
        `description` is what the client's model reads to choose the tool,
        falling back to the operation's summary on a `tool` route. Name and
        describe a route for that reader.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        method : CreateHostedApiRouteRequestMethod

        path : str
            Lowercase segments of letters, digits, `. _ -` or a `{param}`; `/openapi.json`, `/_runs` and `/mcp` are reserved.

        resolver : HostedApiResolver

        idempotency_key : typing.Optional[str]
            A client-generated key (an opaque string, max 255 chars) that makes a
            side-effect POST safe to retry: the server runs the operation exactly
            once and replays the first response (its status and body) for 24 hours.
            Reusing a key with a different request body, or while the first request
            is still in flight, returns `409 idempotency_conflict`. A replayed
            response carries the `Idempotent-Replayed: true` header.

        name : typing.Optional[str]
            The route's name, 1-128 letters, digits, spaces, `.`, `_` or `-`.
            On an API with `mcp_enabled` the MCP tool's name comes from it:
            each run of other characters (a space included) becomes `_`,
            leading and trailing `_` are dropped, and the result is cut to 64
            characters. A route with no name is listed under a name built from
            its method and path, and a name two routes would share takes `_2`,
            `_3` in route order; the face's `tools/list` is the authority. Pick
            a verb-first name a model can choose by.

        description : typing.Optional[str]
            What the route does. On an API with `mcp_enabled` it is the MCP
            tool description a client's model reads to choose the tool, so say
            what it returns and when to call it; a `tool` route with none falls
            back to the operation's summary.

        response_schema : typing.Optional[typing.Dict[str, typing.Any]]

        cache_ttl_seconds : typing.Optional[int]

        enabled : typing.Optional[bool]
            Enabled when omitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiRoute
            The created route.

        Examples
        --------
        import asyncio

        from speechify import (
            AsyncSpeechify,
            HostedApiResolver,
            HostedApiResolverOrderBy,
        )

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.routes.create_route(
                api_id="api_01kc4q3r9s6t8v0w2x4y6z8a0b",
                method="GET",
                path="/leads",
                name="list_leads",
                description="List leads, highest value first.",
                resolver=HostedApiResolver(
                    type="store_query",
                    store_id="store_01kc4q5t1v3w5x7y9z1a3b5c7d",
                    collection="leads",
                    order_by=HostedApiResolverOrderBy(
                        field="value",
                        direction="desc",
                    ),
                ),
                cache_ttl_seconds=30,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_route(
            api_id,
            method=method,
            path=path,
            resolver=resolver,
            idempotency_key=idempotency_key,
            name=name,
            description=description,
            response_schema=response_schema,
            cache_ttl_seconds=cache_ttl_seconds,
            enabled=enabled,
            request_options=request_options,
        )
        return _response.data

    async def mount_routes(
        self,
        api_id: str,
        *,
        tool_id: str,
        idempotency_key: typing.Optional[str] = None,
        operations: typing.Optional[typing.Sequence[str]] = OMIT,
        name_prefix: typing.Optional[str] = OMIT,
        path_prefix: typing.Optional[str] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        include_writes: typing.Optional[bool] = OMIT,
        plan_digest: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApiMount:
        """
        Publish a connector's operations onto the API in one call: one `tool`
        route per operation of an `openapi` tool definition, or per tool its
        `mcp` server lists, named `<name_prefix>__<operation>` at
        `<path_prefix>/<operation>`, so two connectors' tools stay apart on
        the MCP face and inside its 64-character tool names.

        Send `dry_run: true` first. The answer lists every operation with
        its effective `action_class` and `approval`, whether a route can serve
        it, and the `action` a mount takes: `create`, `update` (an MCP tool
        whose input schema changed since its route was written; `changes`
        names what), `unchanged`, `skip` (with the `reason`: not selected, not
        a read, not auto-approved, a name or path already taken, or the route
        cap) or `stale` (a route whose operation the connector no longer
        offers, or can no longer serve; it is reported and never deleted,
        since a consumer may still call it). The same call without `dry_run`
        writes every create and update in one transaction and returns the
        written `route` on each.

        Every answer carries a `plan_digest`. Send the preview's digest with
        the apply: the apply plans again inside its transaction and writes
        only when that plan still has the digest, so a tool the server changed
        or a route edited after you reviewed is never written unseen. When it
        differs the apply writes nothing and answers 409 `mount_plan_changed`
        with the current plan, as a dry run answers it, in
        `error.details.plan`; review that and apply again with its digest,
        under a new `Idempotency-Key` if you sent one, since a key replays its
        first answer, this 409 included. The digest covers every operation the
        connector offers and every route the API holds for it whatever
        `operations` selects, so a preview of everything and an apply of a
        selection share one. An apply without it writes whatever the mount
        plans at that moment.

        Mounting again is the refresh. Every route the API holds for the
        connector is compared with what it offers now, whatever its name,
        path or the selection, so an upstream change is seen as a diff before
        anyone's client sees it. `operations` selects what to create; omit it
        to create a route for every operation a route can serve. A route an
        owner renamed or moved keeps its name and path on refresh.

        The route write's rules apply to every operation: the connector must
        be in the API's project (409 `cross_project_reference`), an MCP server
        must be reachable with its credential to be listed (400
        `validation_failed` on `tool_id` with the server's reason), and a
        public API mounts nothing. An API holds at most 200 routes; a mount
        that would pass the cap skips what does not fit. Without a
        `plan_digest`, a route changed while the mount was being planned
        answers 409 `api_route_conflict`; mount again.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        tool_id : str
            The `openapi` or `mcp` tool definition to mount, in the API's project.

        idempotency_key : typing.Optional[str]
            A client-generated key (an opaque string, max 255 chars) that makes a
            side-effect POST safe to retry: the server runs the operation exactly
            once and replays the first response (its status and body) for 24 hours.
            Reusing a key with a different request body, or while the first request
            is still in flight, returns `409 idempotency_conflict`. A replayed
            response carries the `Idempotent-Replayed: true` header.

        operations : typing.Optional[typing.Sequence[str]]
            The operations to create routes for: openapi operation ids or the
            MCP server's tool names. Omit to create a route for every operation
            a route can serve. Naming one the connector does not offer is 400
            `validation_failed` on `operations[i]`. Existing routes are compared
            whatever the selection.

        name_prefix : typing.Optional[str]
            Prefix of each created route's name, `<name_prefix>__<operation>`. Defaults to the tool's name with other characters as `_`.

        path_prefix : typing.Optional[str]
            Path each created route sits under, `<path_prefix>/<operation>`; lowercase segments of letters, digits, `.`, `_` or `-`, with no `{param}` or `*`, and not under `/mcp`, `/openapi.json` or `/_runs`. Defaults to `/<name_prefix>` in lowercase.

        dry_run : typing.Optional[bool]
            Answer what the mount would do and write nothing.

        include_writes : typing.Optional[bool]
            Create routes for operations that are not reads too, each with
            `allow_write: true`. Only an API whose `auth_mode` names a person
            takes them; the operation's `approval` must still be `auto`.
            Without it a write is a `skip` that says so.

        plan_digest : typing.Optional[str]
            The `plan_digest` of the preview you reviewed. The apply writes
            only while the plan it computes inside its transaction still has
            this digest, and otherwise writes nothing and answers 409
            `mount_plan_changed` with the current plan. Omit it to apply what
            the mount plans now. Refused with `dry_run`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiMount
            What the mount did, or on a dry run would do.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.routes.mount_routes(
                api_id="api_01kc4q3r9s6t8v0w2x4y6z8a0b",
                tool_id="tool_01kc4n9s3v7w0y4a6c8e2g4j6m",
                name_prefix="linear",
                dry_run=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.mount_routes(
            api_id,
            tool_id=tool_id,
            idempotency_key=idempotency_key,
            operations=operations,
            name_prefix=name_prefix,
            path_prefix=path_prefix,
            dry_run=dry_run,
            include_writes=include_writes,
            plan_digest=plan_digest,
            request_options=request_options,
        )
        return _response.data

    async def get_route(
        self, api_id: str, route_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HostedApiRoute:
        """
        Retrieve one route.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        route_id : str
            Route id (prefixed external id, `route_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiRoute
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.routes.get_route(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
                route_id="route_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_route(api_id, route_id, request_options=request_options)
        return _response.data

    async def delete_route(
        self, api_id: str, route_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete a route.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        route_id : str
            Route id (prefixed external id, `route_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.routes.delete_route(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
                route_id="route_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_route(api_id, route_id, request_options=request_options)
        return _response.data

    async def update_route(
        self,
        api_id: str,
        route_id: str,
        *,
        method: typing.Optional[UpdateHostedApiRouteRequestMethod] = OMIT,
        path: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        resolver: typing.Optional[HostedApiResolver] = OMIT,
        response_schema: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        cache_ttl_seconds: typing.Optional[int] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApiRoute:
        """
        Update a route (merge-patch); a changed method or resolver is re-validated.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        route_id : str
            Route id (prefixed external id, `route_...`).

        method : typing.Optional[UpdateHostedApiRouteRequestMethod]

        path : typing.Optional[str]

        name : typing.Optional[str]
            The route's name, 1-128 letters, digits, spaces, `.`, `_` or `-`.
            On an API with `mcp_enabled` the MCP tool's name comes from it:
            each run of other characters (a space included) becomes `_`,
            leading and trailing `_` are dropped, and the result is cut to 64
            characters. A route with no name is listed under a name built from
            its method and path, and a name two routes would share takes `_2`,
            `_3` in route order; the face's `tools/list` is the authority. Pick
            a verb-first name a model can choose by.

        description : typing.Optional[str]
            What the route does. On an API with `mcp_enabled` it is the MCP
            tool description a client's model reads to choose the tool, so say
            what it returns and when to call it; a `tool` route with none falls
            back to the operation's summary.

        resolver : typing.Optional[HostedApiResolver]

        response_schema : typing.Optional[typing.Dict[str, typing.Any]]

        cache_ttl_seconds : typing.Optional[int]

        enabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiRoute
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.routes.update_route(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
                route_id="route_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_route(
            api_id,
            route_id,
            method=method,
            path=path,
            name=name,
            description=description,
            resolver=resolver,
            response_schema=response_schema,
            cache_ttl_seconds=cache_ttl_seconds,
            enabled=enabled,
            request_options=request_options,
        )
        return _response.data
