# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AudioOutputFormat,
        AudioStreamOutputFormat,
        ConsentChallenge,
        Error,
        ErrorCode,
        ErrorDetail,
        GetSpeechOptionsRequest,
        GetSpeechResponse,
        GetSpeechResponseAudioFormat,
        GetStreamOptionsRequest,
        GetStreamRequest,
        GetStreamRequestModel,
        GetVoice,
        GetVoiceGender,
        GetVoiceLanguage,
        GetVoiceType,
        GetVoicesModel,
        GetVoicesModelName,
        ListVoicesResponse,
        Model,
        ModelsResponse,
        NestedChunk,
        PaginationMeta,
        SpeechChunkEvent,
        SpeechDoneEvent,
        SpeechErrorEvent,
        SpeechMarks,
        SpeechStreamEvent,
        SpeechStreamEvent_SpeechChunk,
        SpeechStreamEvent_SpeechDone,
        SpeechStreamEvent_SpeechError,
        WatermarkDetectionResponse,
    )
    from .errors import (
        BadGatewayError,
        BadRequestError,
        ConflictError,
        ContentTooLargeError,
        ForbiddenError,
        InternalServerError,
        NotFoundError,
        PaymentRequiredError,
        ServiceUnavailableError,
        TooManyRequestsError,
        UnauthorizedError,
        UnprocessableEntityError,
    )
    from . import audio, models, voices
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .audio import (
        GetSpeechRequestAudioFormat,
        GetSpeechRequestModel,
        StreamAudioRequestAccept,
        StreamWithTimestampsAudioRequestAccept,
    )
    from .client import AsyncSpeechify, Speechify
    from .environment import SpeechifyEnvironment
    from .version import __version__
    from .voices import CreateVoicesRequestGender, ListVoicesRequestGender, ListVoicesRequestType
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncSpeechify": ".client",
    "AudioOutputFormat": ".types",
    "AudioStreamOutputFormat": ".types",
    "BadGatewayError": ".errors",
    "BadRequestError": ".errors",
    "ConflictError": ".errors",
    "ConsentChallenge": ".types",
    "ContentTooLargeError": ".errors",
    "CreateVoicesRequestGender": ".voices",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "Error": ".types",
    "ErrorCode": ".types",
    "ErrorDetail": ".types",
    "ForbiddenError": ".errors",
    "GetSpeechOptionsRequest": ".types",
    "GetSpeechRequestAudioFormat": ".audio",
    "GetSpeechRequestModel": ".audio",
    "GetSpeechResponse": ".types",
    "GetSpeechResponseAudioFormat": ".types",
    "GetStreamOptionsRequest": ".types",
    "GetStreamRequest": ".types",
    "GetStreamRequestModel": ".types",
    "GetVoice": ".types",
    "GetVoiceGender": ".types",
    "GetVoiceLanguage": ".types",
    "GetVoiceType": ".types",
    "GetVoicesModel": ".types",
    "GetVoicesModelName": ".types",
    "InternalServerError": ".errors",
    "ListVoicesRequestGender": ".voices",
    "ListVoicesRequestType": ".voices",
    "ListVoicesResponse": ".types",
    "Model": ".types",
    "ModelsResponse": ".types",
    "NestedChunk": ".types",
    "NotFoundError": ".errors",
    "PaginationMeta": ".types",
    "PaymentRequiredError": ".errors",
    "ServiceUnavailableError": ".errors",
    "SpeechChunkEvent": ".types",
    "SpeechDoneEvent": ".types",
    "SpeechErrorEvent": ".types",
    "SpeechMarks": ".types",
    "SpeechStreamEvent": ".types",
    "SpeechStreamEvent_SpeechChunk": ".types",
    "SpeechStreamEvent_SpeechDone": ".types",
    "SpeechStreamEvent_SpeechError": ".types",
    "Speechify": ".client",
    "SpeechifyEnvironment": ".environment",
    "StreamAudioRequestAccept": ".audio",
    "StreamWithTimestampsAudioRequestAccept": ".audio",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "WatermarkDetectionResponse": ".types",
    "__version__": ".version",
    "audio": ".audio",
    "models": ".models",
    "voices": ".voices",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncSpeechify",
    "AudioOutputFormat",
    "AudioStreamOutputFormat",
    "BadGatewayError",
    "BadRequestError",
    "ConflictError",
    "ConsentChallenge",
    "ContentTooLargeError",
    "CreateVoicesRequestGender",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "Error",
    "ErrorCode",
    "ErrorDetail",
    "ForbiddenError",
    "GetSpeechOptionsRequest",
    "GetSpeechRequestAudioFormat",
    "GetSpeechRequestModel",
    "GetSpeechResponse",
    "GetSpeechResponseAudioFormat",
    "GetStreamOptionsRequest",
    "GetStreamRequest",
    "GetStreamRequestModel",
    "GetVoice",
    "GetVoiceGender",
    "GetVoiceLanguage",
    "GetVoiceType",
    "GetVoicesModel",
    "GetVoicesModelName",
    "InternalServerError",
    "ListVoicesRequestGender",
    "ListVoicesRequestType",
    "ListVoicesResponse",
    "Model",
    "ModelsResponse",
    "NestedChunk",
    "NotFoundError",
    "PaginationMeta",
    "PaymentRequiredError",
    "ServiceUnavailableError",
    "SpeechChunkEvent",
    "SpeechDoneEvent",
    "SpeechErrorEvent",
    "SpeechMarks",
    "SpeechStreamEvent",
    "SpeechStreamEvent_SpeechChunk",
    "SpeechStreamEvent_SpeechDone",
    "SpeechStreamEvent_SpeechError",
    "Speechify",
    "SpeechifyEnvironment",
    "StreamAudioRequestAccept",
    "StreamWithTimestampsAudioRequestAccept",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "WatermarkDetectionResponse",
    "__version__",
    "audio",
    "models",
    "voices",
]
