# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.hosted_api import HostedApi
from ..types.hosted_api_usage import HostedApiUsage
from ..types.hosted_api_user_token_secret import HostedApiUserTokenSecret
from ..types.list_hosted_ap_is_response import ListHostedApIsResponse
from ..types.request_analytics_response import RequestAnalyticsResponse
from .raw_client import AsyncRawHostedApisClient, RawHostedApisClient
from .types.create_hosted_api_request_auth_mode import CreateHostedApiRequestAuthMode
from .types.get_analytics_hosted_apis_request_granularity import GetAnalyticsHostedApisRequestGranularity
from .types.update_hosted_api_request_auth_mode import UpdateHostedApiRequestAuthMode

if typing.TYPE_CHECKING:
    from .keys.client import AsyncKeysClient, KeysClient
    from .routes.client import AsyncRoutesClient, RoutesClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class HostedApisClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHostedApisClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._routes: typing.Optional[RoutesClient] = None
        self._keys: typing.Optional[KeysClient] = None

    @property
    def with_raw_response(self) -> RawHostedApisClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHostedApisClient
        """
        return self._raw_client

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[HostedApi, ListHostedApIsResponse]:
        """
        List the hosted APIs in the caller's workspace, most recently updated
        first. A hosted API is the API you assemble: a slug that becomes
        `https://<slug>.<hosted-api domain>`, the routes it answers, and the
        consumer keys your own callers present.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        project_id : typing.Optional[str]
            Filter by workspace project: omit for every project you can reach,
            pass the literal `default` for resources in the implicit Default
            project only, or a `proj_...` id for that project's resources.
            Returns 404 project_not_found for a malformed id and for any filter
            outside your reach: a project-pinned API key or service-account key
            reaches only its pinned project, and a member holding project grants
            reaches only the granted projects, so neither can name `default`.
            That 404 is the same in every case and does not reveal whether such
            a project exists - outside your reach a project is answered as
            nonexistent, never as forbidden. Inside it, a well-formed id that
            matches no project yields an empty page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[HostedApi, ListHostedApIsResponse]
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        response = client.hosted_apis.list(
            project_id="proj_01arz3ndektsv4rrffq69g5fav",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(cursor=cursor, limit=limit, project_id=project_id, request_options=request_options)

    def create(
        self,
        *,
        slug: str,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        auth_mode: typing.Optional[CreateHostedApiRequestAuthMode] = OMIT,
        cors_origins: typing.Optional[typing.Sequence[str]] = OMIT,
        daily_run_cap: typing.Optional[int] = OMIT,
        daily_read_cap: typing.Optional[int] = OMIT,
        daily_write_cap: typing.Optional[int] = OMIT,
        mcp_enabled: typing.Optional[bool] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        user_token_jwks_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApi:
        """
        Create a hosted API. The slug is a DNS label, globally unique on the
        shared domain (409 `hosted_api_slug_taken`) and immutable afterwards.
        `auth_mode` names the audience, narrowest first: `owner`, `workspace`
        (the platform's own credentials), `user_token` (a JWT your backend
        signs per user), `consumer_key` (a `ck_` key you mint) or `public`
        (anyone, reads only). A workspace can refuse `public` as policy (403
        `hosted_api_public_refused`). Reads, runs and writes are each bounded
        per UTC day (`daily_read_cap`, `daily_run_cap`, `daily_write_cap`),
        and an API holds only a share of a server's requests open at once, so
        a slow upstream behind one API cannot take the capacity others need:
        past it, a request answers 429 `hosted_api_busy` with `Retry-After`.

        `mcp_enabled: true` also serves the API's routes as an MCP server at
        `POST <base_url>/mcp`, so an MCP client (Claude Code, Cursor) attaches
        to one address and gets them as tools, under the same audience, keys
        and caps. It is refused with `auth_mode: public`. On that face the
        API's `name` is the server's title and its `description` is the
        instructions the client's model reads, so describe what the tools are
        for.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        slug : str
            3-40 lowercase letters, digits or hyphens; a DNS label, unique on the shared domain; immutable.

        name : str

        idempotency_key : typing.Optional[str]
            A client-generated key (an opaque string, max 255 chars) that makes a
            side-effect POST safe to retry: the server runs the operation exactly
            once and replays the first response (its status and body) for 24 hours.
            Reusing a key with a different request body, or while the first request
            is still in flight, returns `409 idempotency_conflict`. A replayed
            response carries the `Idempotent-Replayed: true` header.

        description : typing.Optional[str]
            What the API is for; also the instructions an MCP client hands its model when `mcp_enabled` is on.

        auth_mode : typing.Optional[CreateHostedApiRequestAuthMode]
            consumer_key when omitted. `public` is refused with 403 `hosted_api_public_refused` where the workspace's policy does not allow internet-facing APIs.

        cors_origins : typing.Optional[typing.Sequence[str]]

        daily_run_cap : typing.Optional[int]
            Runs the API may start per UTC day through its run routes; 1000 when omitted.

        daily_read_cap : typing.Optional[int]
            Reads the API's store, file, run_latest and tool routes may serve per UTC day; 100000 when omitted.

        daily_write_cap : typing.Optional[int]
            Documents the API's write routes may land per UTC day; 10000 when omitted.

        mcp_enabled : typing.Optional[bool]
            Serve the routes as an MCP server at `POST <base_url>/mcp` too;
            false when omitted. Refused with `auth_mode: public` (400
            `validation_failed` naming `mcp_enabled`).

        project_id : typing.Optional[str]

        user_token_jwks_url : typing.Optional[str]
            Register the key set end-user tokens are verified against (an `https` URL on a public host).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApi
            The created API.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.create(
            idempotency_key="a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
            slug="acme-news",
            name="Acme News",
        )
        """
        _response = self._raw_client.create(
            slug=slug,
            name=name,
            idempotency_key=idempotency_key,
            description=description,
            auth_mode=auth_mode,
            cors_origins=cors_origins,
            daily_run_cap=daily_run_cap,
            daily_read_cap=daily_read_cap,
            daily_write_cap=daily_write_cap,
            mcp_enabled=mcp_enabled,
            project_id=project_id,
            user_token_jwks_url=user_token_jwks_url,
            request_options=request_options,
        )
        return _response.data

    def get(self, api_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HostedApi:
        """
        Retrieve one hosted API.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApi
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.get(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.get(api_id, request_options=request_options)
        return _response.data

    def delete(self, api_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a hosted API; its host stops answering at once.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.delete(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.delete(api_id, request_options=request_options)
        return _response.data

    def update(
        self,
        api_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        auth_mode: typing.Optional[UpdateHostedApiRequestAuthMode] = OMIT,
        cors_origins: typing.Optional[typing.Sequence[str]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        daily_run_cap: typing.Optional[int] = OMIT,
        daily_read_cap: typing.Optional[int] = OMIT,
        daily_write_cap: typing.Optional[int] = OMIT,
        mcp_enabled: typing.Optional[bool] = OMIT,
        user_token_jwks_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApi:
        """
        Update a hosted API (merge-patch). Switching to `public` is refused
        while a `run` or `store_write` route exists: an anonymous caller must
        not start runs that spend the workspace's budget or write to a store,
        and it is refused outright where the workspace's policy does not allow
        internet-facing APIs (403 `hosted_api_public_refused`). Switching to a
        mode that names no caller (`consumer_key`, `public`) is refused while
        a route binds `{{user.*}}`: only `user_token`, `workspace` and `owner`
        supply a person. Switching to `public` is also refused while a `tool`
        route exists (a vendor call spends the workspace's vendor budget) and
        while `mcp_enabled` is on, and switching the MCP face on is refused on
        a `public` API (400 `validation_failed` naming `mcp_enabled`).
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        name : typing.Optional[str]

        description : typing.Optional[str]
            What the API is for; also the instructions an MCP client hands its model when `mcp_enabled` is on.

        auth_mode : typing.Optional[UpdateHostedApiRequestAuthMode]

        cors_origins : typing.Optional[typing.Sequence[str]]

        enabled : typing.Optional[bool]
            A paused API answers 503 to every consumer request.

        daily_run_cap : typing.Optional[int]

        daily_read_cap : typing.Optional[int]

        daily_write_cap : typing.Optional[int]

        mcp_enabled : typing.Optional[bool]
            Switch the MCP face at `POST <base_url>/mcp` on or off. Refused with
            400 `validation_failed` naming `mcp_enabled` when the API is, or is
            being made, `public`. Allow up to 15 seconds for the switch, like
            any route change, to reach every server.

        user_token_jwks_url : typing.Optional[str]
            Replace the registered key set; an empty string removes it, after which the signing secret verifies tokens again.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApi
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.update(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.update(
            api_id,
            name=name,
            description=description,
            auth_mode=auth_mode,
            cors_origins=cors_origins,
            enabled=enabled,
            daily_run_cap=daily_run_cap,
            daily_read_cap=daily_read_cap,
            daily_write_cap=daily_write_cap,
            mcp_enabled=mcp_enabled,
            user_token_jwks_url=user_token_jwks_url,
            request_options=request_options,
        )
        return _response.data

    def get_open_api(
        self, api_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        The OpenAPI 3.1 document describing the hosted API's routes - the same
        document the API serves to its consumers at `/openapi.json`. A `tool`
        route's request body is the operation's own argument schema. When
        `mcp_enabled` is on, the document carries an `x-speechify-mcp` object
        (`url`, `transport: streamable-http`, `description`) naming where an
        MCP client attaches; the face speaks JSON-RPC, so it is an extension
        rather than a path.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            The OpenAPI document.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.get_open_api(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.get_open_api(api_id, request_options=request_options)
        return _response.data

    def get_usage(self, api_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HostedApiUsage:
        """
        Today's reads, runs and writes against the API's daily caps, with each
        route's share of the reads and writes. A read is a request a store,
        file or run_latest route answered from storage; a response served from
        the cache is not one. A write is a document a `store_write` route
        landed; a replayed Idempotency-Key is not one. `counters_available` is false where nothing counts (no Redis), so
        a zero is never mistaken for a quiet day.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiUsage
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.get_usage(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.get_usage(api_id, request_options=request_options)
        return _response.data

    def get_analytics(
        self,
        api_id: str,
        *,
        start: typing.Optional[dt.datetime] = None,
        end: typing.Optional[dt.datetime] = None,
        granularity: typing.Optional[GetAnalyticsHostedApisRequestGranularity] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RequestAnalyticsResponse:
        """
        Requests the API served over time: volume split by status, success
        rate, and p50/p95/p99 latency per time bucket, plus one `top_paths`
        row per route, busiest first, naming the route by `route_id`. Every
        request its host answered counts, including refusals such as a
        missing key (401) or an exhausted rate limit (429); `top_paths` counts
        only the requests that matched a route, including a route an MCP
        client called by tool name.
        The window defaults to the last 7 days and is capped at 30.

        History starts at `history_starts_at`, the first request in the last
        30 days attributed to this API: requests before it cannot be
        attributed, so a bucket before it is missing data, not a quiet period.
        When `history_starts_at` is absent, no request to this API has been
        attributed in the last 30 days, and no bucket is known to be complete.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        start : typing.Optional[dt.datetime]
            Inclusive start of the window (RFC-3339). Defaults to 7 days ago; the window is capped at 30 days.

        end : typing.Optional[dt.datetime]
            Exclusive end of the window (RFC-3339). Defaults to now.

        granularity : typing.Optional[GetAnalyticsHostedApisRequestGranularity]
            Time-bucket size for the analytics series.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RequestAnalyticsResponse
            OK

        Examples
        --------
        import datetime

        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.get_analytics(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            start=datetime.datetime.fromisoformat(
                "2026-06-23 00:00:00+00:00",
            ),
            end=datetime.datetime.fromisoformat(
                "2026-06-30 00:00:00+00:00",
            ),
        )
        """
        _response = self._raw_client.get_analytics(
            api_id, start=start, end=end, granularity=granularity, request_options=request_options
        )
        return _response.data

    def rotate_user_token_secret(
        self,
        api_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApiUserTokenSecret:
        """
        Mint the signing secret end-user tokens are verified against, replacing
        any previous one at once: every token signed with the old secret stops
        verifying. The plaintext is in this response and nowhere else; later
        reads show `user_token_secret_hint`. Your backend signs a JWT with it
        (HS256) carrying `sub` (the user, at most 256 characters) and `exp`
        (within 24 hours), and the consumer presents it as
        `Authorization: Bearer <token>`. Register `user_token_jwks_url`
        instead to verify with your own keys.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        idempotency_key : typing.Optional[str]
            A client-generated key (an opaque string, max 255 chars) that makes a
            side-effect POST safe to retry: the server runs the operation exactly
            once and replays the first response (its status and body) for 24 hours.
            Reusing a key with a different request body, or while the first request
            is still in flight, returns `409 idempotency_conflict`. A replayed
            response carries the `Idempotent-Replayed: true` header.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiUserTokenSecret
            OK

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.hosted_apis.rotate_user_token_secret(
            api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            idempotency_key="a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
        )
        """
        _response = self._raw_client.rotate_user_token_secret(
            api_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    @property
    def routes(self):
        if self._routes is None:
            from .routes.client import RoutesClient  # noqa: E402

            self._routes = RoutesClient(client_wrapper=self._client_wrapper)
        return self._routes

    @property
    def keys(self):
        if self._keys is None:
            from .keys.client import KeysClient  # noqa: E402

            self._keys = KeysClient(client_wrapper=self._client_wrapper)
        return self._keys


class AsyncHostedApisClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHostedApisClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._routes: typing.Optional[AsyncRoutesClient] = None
        self._keys: typing.Optional[AsyncKeysClient] = None

    @property
    def with_raw_response(self) -> AsyncRawHostedApisClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHostedApisClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[HostedApi, ListHostedApIsResponse]:
        """
        List the hosted APIs in the caller's workspace, most recently updated
        first. A hosted API is the API you assemble: a slug that becomes
        `https://<slug>.<hosted-api domain>`, the routes it answers, and the
        consumer keys your own callers present.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        project_id : typing.Optional[str]
            Filter by workspace project: omit for every project you can reach,
            pass the literal `default` for resources in the implicit Default
            project only, or a `proj_...` id for that project's resources.
            Returns 404 project_not_found for a malformed id and for any filter
            outside your reach: a project-pinned API key or service-account key
            reaches only its pinned project, and a member holding project grants
            reaches only the granted projects, so neither can name `default`.
            That 404 is the same in every case and does not reveal whether such
            a project exists - outside your reach a project is answered as
            nonexistent, never as forbidden. Inside it, a well-formed id that
            matches no project yields an empty page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[HostedApi, ListHostedApIsResponse]
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.hosted_apis.list(
                project_id="proj_01arz3ndektsv4rrffq69g5fav",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            cursor=cursor, limit=limit, project_id=project_id, request_options=request_options
        )

    async def create(
        self,
        *,
        slug: str,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        auth_mode: typing.Optional[CreateHostedApiRequestAuthMode] = OMIT,
        cors_origins: typing.Optional[typing.Sequence[str]] = OMIT,
        daily_run_cap: typing.Optional[int] = OMIT,
        daily_read_cap: typing.Optional[int] = OMIT,
        daily_write_cap: typing.Optional[int] = OMIT,
        mcp_enabled: typing.Optional[bool] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        user_token_jwks_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApi:
        """
        Create a hosted API. The slug is a DNS label, globally unique on the
        shared domain (409 `hosted_api_slug_taken`) and immutable afterwards.
        `auth_mode` names the audience, narrowest first: `owner`, `workspace`
        (the platform's own credentials), `user_token` (a JWT your backend
        signs per user), `consumer_key` (a `ck_` key you mint) or `public`
        (anyone, reads only). A workspace can refuse `public` as policy (403
        `hosted_api_public_refused`). Reads, runs and writes are each bounded
        per UTC day (`daily_read_cap`, `daily_run_cap`, `daily_write_cap`),
        and an API holds only a share of a server's requests open at once, so
        a slow upstream behind one API cannot take the capacity others need:
        past it, a request answers 429 `hosted_api_busy` with `Retry-After`.

        `mcp_enabled: true` also serves the API's routes as an MCP server at
        `POST <base_url>/mcp`, so an MCP client (Claude Code, Cursor) attaches
        to one address and gets them as tools, under the same audience, keys
        and caps. It is refused with `auth_mode: public`. On that face the
        API's `name` is the server's title and its `description` is the
        instructions the client's model reads, so describe what the tools are
        for.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        slug : str
            3-40 lowercase letters, digits or hyphens; a DNS label, unique on the shared domain; immutable.

        name : str

        idempotency_key : typing.Optional[str]
            A client-generated key (an opaque string, max 255 chars) that makes a
            side-effect POST safe to retry: the server runs the operation exactly
            once and replays the first response (its status and body) for 24 hours.
            Reusing a key with a different request body, or while the first request
            is still in flight, returns `409 idempotency_conflict`. A replayed
            response carries the `Idempotent-Replayed: true` header.

        description : typing.Optional[str]
            What the API is for; also the instructions an MCP client hands its model when `mcp_enabled` is on.

        auth_mode : typing.Optional[CreateHostedApiRequestAuthMode]
            consumer_key when omitted. `public` is refused with 403 `hosted_api_public_refused` where the workspace's policy does not allow internet-facing APIs.

        cors_origins : typing.Optional[typing.Sequence[str]]

        daily_run_cap : typing.Optional[int]
            Runs the API may start per UTC day through its run routes; 1000 when omitted.

        daily_read_cap : typing.Optional[int]
            Reads the API's store, file, run_latest and tool routes may serve per UTC day; 100000 when omitted.

        daily_write_cap : typing.Optional[int]
            Documents the API's write routes may land per UTC day; 10000 when omitted.

        mcp_enabled : typing.Optional[bool]
            Serve the routes as an MCP server at `POST <base_url>/mcp` too;
            false when omitted. Refused with `auth_mode: public` (400
            `validation_failed` naming `mcp_enabled`).

        project_id : typing.Optional[str]

        user_token_jwks_url : typing.Optional[str]
            Register the key set end-user tokens are verified against (an `https` URL on a public host).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApi
            The created API.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.create(
                idempotency_key="a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
                slug="acme-news",
                name="Acme News",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            slug=slug,
            name=name,
            idempotency_key=idempotency_key,
            description=description,
            auth_mode=auth_mode,
            cors_origins=cors_origins,
            daily_run_cap=daily_run_cap,
            daily_read_cap=daily_read_cap,
            daily_write_cap=daily_write_cap,
            mcp_enabled=mcp_enabled,
            project_id=project_id,
            user_token_jwks_url=user_token_jwks_url,
            request_options=request_options,
        )
        return _response.data

    async def get(self, api_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HostedApi:
        """
        Retrieve one hosted API.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApi
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.get(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(api_id, request_options=request_options)
        return _response.data

    async def delete(self, api_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a hosted API; its host stops answering at once.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.delete(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(api_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        api_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        auth_mode: typing.Optional[UpdateHostedApiRequestAuthMode] = OMIT,
        cors_origins: typing.Optional[typing.Sequence[str]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        daily_run_cap: typing.Optional[int] = OMIT,
        daily_read_cap: typing.Optional[int] = OMIT,
        daily_write_cap: typing.Optional[int] = OMIT,
        mcp_enabled: typing.Optional[bool] = OMIT,
        user_token_jwks_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApi:
        """
        Update a hosted API (merge-patch). Switching to `public` is refused
        while a `run` or `store_write` route exists: an anonymous caller must
        not start runs that spend the workspace's budget or write to a store,
        and it is refused outright where the workspace's policy does not allow
        internet-facing APIs (403 `hosted_api_public_refused`). Switching to a
        mode that names no caller (`consumer_key`, `public`) is refused while
        a route binds `{{user.*}}`: only `user_token`, `workspace` and `owner`
        supply a person. Switching to `public` is also refused while a `tool`
        route exists (a vendor call spends the workspace's vendor budget) and
        while `mcp_enabled` is on, and switching the MCP face on is refused on
        a `public` API (400 `validation_failed` naming `mcp_enabled`).
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        name : typing.Optional[str]

        description : typing.Optional[str]
            What the API is for; also the instructions an MCP client hands its model when `mcp_enabled` is on.

        auth_mode : typing.Optional[UpdateHostedApiRequestAuthMode]

        cors_origins : typing.Optional[typing.Sequence[str]]

        enabled : typing.Optional[bool]
            A paused API answers 503 to every consumer request.

        daily_run_cap : typing.Optional[int]

        daily_read_cap : typing.Optional[int]

        daily_write_cap : typing.Optional[int]

        mcp_enabled : typing.Optional[bool]
            Switch the MCP face at `POST <base_url>/mcp` on or off. Refused with
            400 `validation_failed` naming `mcp_enabled` when the API is, or is
            being made, `public`. Allow up to 15 seconds for the switch, like
            any route change, to reach every server.

        user_token_jwks_url : typing.Optional[str]
            Replace the registered key set; an empty string removes it, after which the signing secret verifies tokens again.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApi
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.update(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            api_id,
            name=name,
            description=description,
            auth_mode=auth_mode,
            cors_origins=cors_origins,
            enabled=enabled,
            daily_run_cap=daily_run_cap,
            daily_read_cap=daily_read_cap,
            daily_write_cap=daily_write_cap,
            mcp_enabled=mcp_enabled,
            user_token_jwks_url=user_token_jwks_url,
            request_options=request_options,
        )
        return _response.data

    async def get_open_api(
        self, api_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        The OpenAPI 3.1 document describing the hosted API's routes - the same
        document the API serves to its consumers at `/openapi.json`. A `tool`
        route's request body is the operation's own argument schema. When
        `mcp_enabled` is on, the document carries an `x-speechify-mcp` object
        (`url`, `transport: streamable-http`, `description`) naming where an
        MCP client attaches; the face speaks JSON-RPC, so it is an extension
        rather than a path.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            The OpenAPI document.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.get_open_api(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_open_api(api_id, request_options=request_options)
        return _response.data

    async def get_usage(
        self, api_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HostedApiUsage:
        """
        Today's reads, runs and writes against the API's daily caps, with each
        route's share of the reads and writes. A read is a request a store,
        file or run_latest route answered from storage; a response served from
        the cache is not one. A write is a document a `store_write` route
        landed; a replayed Idempotency-Key is not one. `counters_available` is false where nothing counts (no Redis), so
        a zero is never mistaken for a quiet day.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiUsage
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.get_usage(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_usage(api_id, request_options=request_options)
        return _response.data

    async def get_analytics(
        self,
        api_id: str,
        *,
        start: typing.Optional[dt.datetime] = None,
        end: typing.Optional[dt.datetime] = None,
        granularity: typing.Optional[GetAnalyticsHostedApisRequestGranularity] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RequestAnalyticsResponse:
        """
        Requests the API served over time: volume split by status, success
        rate, and p50/p95/p99 latency per time bucket, plus one `top_paths`
        row per route, busiest first, naming the route by `route_id`. Every
        request its host answered counts, including refusals such as a
        missing key (401) or an exhausted rate limit (429); `top_paths` counts
        only the requests that matched a route, including a route an MCP
        client called by tool name.
        The window defaults to the last 7 days and is capped at 30.

        History starts at `history_starts_at`, the first request in the last
        30 days attributed to this API: requests before it cannot be
        attributed, so a bucket before it is missing data, not a quiet period.
        When `history_starts_at` is absent, no request to this API has been
        attributed in the last 30 days, and no bucket is known to be complete.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        start : typing.Optional[dt.datetime]
            Inclusive start of the window (RFC-3339). Defaults to 7 days ago; the window is capped at 30 days.

        end : typing.Optional[dt.datetime]
            Exclusive end of the window (RFC-3339). Defaults to now.

        granularity : typing.Optional[GetAnalyticsHostedApisRequestGranularity]
            Time-bucket size for the analytics series.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RequestAnalyticsResponse
            OK

        Examples
        --------
        import asyncio
        import datetime

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.get_analytics(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
                start=datetime.datetime.fromisoformat(
                    "2026-06-23 00:00:00+00:00",
                ),
                end=datetime.datetime.fromisoformat(
                    "2026-06-30 00:00:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_analytics(
            api_id, start=start, end=end, granularity=granularity, request_options=request_options
        )
        return _response.data

    async def rotate_user_token_secret(
        self,
        api_id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HostedApiUserTokenSecret:
        """
        Mint the signing secret end-user tokens are verified against, replacing
        any previous one at once: every token signed with the old secret stops
        verifying. The plaintext is in this response and nowhere else; later
        reads show `user_token_secret_hint`. Your backend signs a JWT with it
        (HS256) carrying `sub` (the user, at most 256 characters) and `exp`
        (within 24 hours), and the consumer presents it as
        `Authorization: Bearer <token>`. Register `user_token_jwks_url`
        instead to verify with your own keys.
        Dark launch: requires the `hosted_apis_access` entitlement (402 `hosted_apis_not_in_plan` otherwise).

        Parameters
        ----------
        api_id : str
            Hosted API id (prefixed external id, `api_...`).

        idempotency_key : typing.Optional[str]
            A client-generated key (an opaque string, max 255 chars) that makes a
            side-effect POST safe to retry: the server runs the operation exactly
            once and replays the first response (its status and body) for 24 hours.
            Reusing a key with a different request body, or while the first request
            is still in flight, returns `409 idempotency_conflict`. A replayed
            response carries the `Idempotent-Replayed: true` header.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HostedApiUserTokenSecret
            OK

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.hosted_apis.rotate_user_token_secret(
                api_id="api_01jqr8x9zg5k2m3n4p5q6r7s8t",
                idempotency_key="a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_user_token_secret(
            api_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    @property
    def routes(self):
        if self._routes is None:
            from .routes.client import AsyncRoutesClient  # noqa: E402

            self._routes = AsyncRoutesClient(client_wrapper=self._client_wrapper)
        return self._routes

    @property
    def keys(self):
        if self._keys is None:
            from .keys.client import AsyncKeysClient  # noqa: E402

            self._keys = AsyncKeysClient(client_wrapper=self._client_wrapper)
        return self._keys
