# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_close_type import InputCloseType


class InputClose(UniversalBaseModel):
    """
    Client message on GET /v1/audio/stream/ws: no more text is coming. The server speaks everything it was sent, sends speech.done with reason closed, and closes the socket. Keep reading until speech.done arrives: closing the socket first abandons the audio still to come, and the segment it cuts is billed in full.
    """

    type: InputCloseType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
