# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .speech_error_error_code import SpeechErrorErrorCode


class SpeechErrorError(UniversalBaseModel):
    code: SpeechErrorErrorCode = pydantic.Field()
    """
    Stable machine-readable error code. Additive only: codes are
    never renamed, only deprecated. SDKs may map each code to a
    typed exception class. Status-code semantics:
    4xx codes describe caller-fixable issues; 5xx codes describe
    server-side failures and are safe to retry with backoff for
    idempotent requests.
    """

    message: str = pydantic.Field()
    """
    Human-readable explanation of this specific occurrence.
    Safe to surface in UI banners or pass to support. The
    wording can change between releases; clients should
    match on `code`, not on the message string.
    """

    fields: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Per-field validation errors as `path -> message`. Only
    present on 400 responses caused by request validation
    (typically code=`validation_failed`). Keys are field
    paths in dotted/bracket notation; values are short
    human explanations safe to inline-surface next to the
    offending form field.
    """

    details: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Structured, endpoint-specific context beyond the flat
    `fields` map. Present only on the few errors that carry
    it (e.g. the `used_by` referrer list on a credential
    delete-conflict); its shape depends on the error `code`.
    Clients that don't recognise a `details` shape can ignore
    it - the `code` + `message` contract is unchanged.
    """

    docs_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Link to the documentation that resolves this class of
    error, when a stable page exists. Rate and concurrency
    429s link the API limits reference, which lists each
    plan's limits and how to raise them.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
