# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_voice_gender import GetVoiceGender
from .get_voice_type import GetVoiceType
from .get_voices_model import GetVoicesModel


class GetVoice(UniversalBaseModel):
    avatar_image: typing.Optional[str] = None
    display_name: str
    gender: GetVoiceGender
    locale: str
    id: str
    models: typing.List[GetVoicesModel]
    preview_audio: typing.Optional[str] = None
    project_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The workspace project this cloned voice is filed under, set when
    a project-pinned key created it. Returned wherever a cloned voice
    is: the list, a single-voice read, and the create response.
    
    Omitted for a shared-catalog voice and for a cloned voice no
    project filed, which is shared with the whole workspace and
    listed for every member of it.
    """

    tags: typing.Optional[typing.List[str]] = None
    type: GetVoiceType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
