# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_voice_gender import GetVoiceGender
from .get_voice_type import GetVoiceType
from .get_voices_model import GetVoicesModel


class GetVoice(UniversalBaseModel):
    avatar_image: typing.Optional[str] = None
    display_name: str
    gender: GetVoiceGender
    locale: str
    id: str
    models: typing.List[GetVoicesModel]
    preview_audio: typing.Optional[str] = None
    project_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The workspace project this cloned voice is filed under, set when
    a project-pinned key created it. Returned on a single-voice read,
    on the create response, and on a list narrowed with the
    `project_id` parameter.
    
    Omitted for a shared-catalog voice, for a cloned voice the
    workspace holds at large, and on an unnarrowed list, where the
    catalog read does not carry each voice's project.
    """

    tags: typing.Optional[typing.List[str]] = None
    type: GetVoiceType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
