# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class HostedApiUsageRoutesItem(UniversalBaseModel):
    route_id: str
    reads: int
    writes: int
    tool_calls: typing.Optional[int] = pydantic.Field(default=None)
    """
    For a `tool` route, the calls its connector was asked to answer today, whatever the outcome.
    """

    upstream_errors: typing.Optional[int] = pydantic.Field(default=None)
    """
    For a `tool` route, today's calls the connector answered with an error or never answered (502 `route_upstream_error`).
    """

    upstream_throttles: typing.Optional[int] = pydantic.Field(default=None)
    """
    For a `tool` route, today's calls throttled by the tool's `max_requests_per_minute` or by the connector (429 `route_upstream_rate_limited`).
    """

    upstream_latency_ms_mean: typing.Optional[int] = pydantic.Field(default=None)
    """
    For a `tool` route, the mean time today's calls took, in milliseconds, connector included; null before the first call. A slow or failing connector shows here rather than as a slow API.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
