# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class HostedApiUserTokenSecret(UniversalBaseModel):
    secret: str = pydantic.Field()
    """
    The plaintext signing secret, present on this response only. Sign end-user tokens with it (HS256).
    """

    secret_hint: str = pydantic.Field()
    """
    The masked form every later read shows as `user_token_secret_hint`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
