# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Model(UniversalBaseModel):
    """
    One selectable text-to-speech model.
    """

    id: str = pydantic.Field()
    """
    Model identifier. Pass this as the `model` parameter to
    POST /v1/audio/speech or /v1/audio/stream.
    """

    name: str = pydantic.Field()
    """
    Human-readable model name, for a model picker.
    """

    default: bool = pydantic.Field()
    """
    Whether this is the model used when a synthesis request omits
    `model`. Exactly one model in the list is the default. Distinct
    from `recommended`: the default accepts every voice, while the
    recommended model may serve a curated or English-only set.
    """

    recommended: bool = pydantic.Field()
    """
    Whether this is the model we recommend for new integrations.
    Exactly one model in the list is recommended, and it may differ
    from the `default`.
    """

    deprecated: bool = pydantic.Field()
    """
    Whether this is a legacy model. De-emphasise it in a picker and
    steer new integrations to a current model. Read `retired_at` for
    whether it also has a withdrawal date.
    """

    retired_at: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    The API version at which this model stops being selectable, as
    `YYYY-MM-DD`. Absent when the model has no withdrawal date.
    
    It appears only while your workspace is pinned BELOW that version -
    at or after it the model is absent from this catalog entirely, and
    naming it returns 400 `model_retired`. So a present value means "you
    can still use this, and this is the date you lose it". Pinning your
    API version before this date keeps the model working, up to
    `sunset_at`.
    """

    sunset_at: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    The date this model is switched off, as `YYYY-MM-DD`. Absent when no
    shutdown is scheduled.
    
    This is the deadline `retired_at`'s version pin runs out against:
    from `sunset_at` the model is unreachable on EVERY API version,
    including a workspace pinned below its retirement. Read the two
    together - a pin buys time to migrate, not a permanent exemption.
    """

    description: str = pydantic.Field()
    """
    One-line summary of the model, for a model picker.
    """

    languages: typing.List[str] = pydantic.Field()
    """
    Languages the model can synthesize, as BCP-47 locale strings
    matching the `language` request parameter (e.g. `en`, `fr-FR`).
    English-only models return `["en"]`. This set reflects current
    capability and can grow over time.
    """

    endpoints: typing.List[str] = pydantic.Field()
    """
    The synthesis routes this model may be passed to. Only the
    streaming-native models serve `/v1/audio/stream/with-timestamps`;
    passing a model this list omits is a 400 rather than a degraded
    response, so branch on it instead of discovering it at call time.
    """

    curated_voices: bool = pydantic.Field()
    """
    Whether the model's stock voices are restricted to the set curated
    for it. When true, pick a stock voice whose `models` array in
    GET /v1/voices names this model; any other stock voice is rejected.
    When false, every stock catalogue voice works. Cloned voices are
    governed separately - always read each voice's own `models` array in
    GET /v1/voices, which reflects what your workspace may actually
    synthesize.
    """

    english_voices_only: bool = pydantic.Field()
    """
    Whether the model rejects a non-English voice. Independent of
    `languages`: a model can publish English only and still accept any
    voice.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
