# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .model import Model


class ModelsResponse(UniversalBaseModel):
    """
    The catalog of text-to-speech models available for synthesis.
    """

    models: typing.List[Model] = pydantic.Field()
    """
    The models selectable on the single-utterance synthesis endpoints.
    """

    dialogue_models: typing.List[Model] = pydantic.Field()
    """
    The multi-speaker models selectable on POST /v1/audio/dialogue.
    Disjoint from `models`: a dialogue model consumes a
    speaker-attributed script rather than one utterance, so it is
    rejected on the single-utterance endpoints and vice versa. Its
    `default` marks the model that endpoint resolves to when a request
    omits `model`, independently of the `models` default.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
