# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProjectStillRevokedCounts(UniversalBaseModel):
    """
    What the restore deliberately left revoked: the credentials the purge
    killed. Every field is a real count, including zero.
    """

    api_keys: typing.Optional[int] = None
    service_accounts: typing.Optional[int] = None
    credentials: typing.Optional[int] = None
    webhook_endpoints: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
