# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .project_monthly_budget_status import ProjectMonthlyBudgetStatus


class Project(UniversalBaseModel):
    """
    A workspace project: a resource grouping that a member grant or a
    credential pin can also scope. Resources reference a project by id;
    a resource with no `project_id` lives in the implicit Default
    project. A project can carry member grants, which scope a granted
    member to the projects they hold, and the invoice stays
    workspace-level with no billing split. A project may carry a monthly
    spend LIMIT, which bounds work without splitting the bill, capacity
    CEILINGS such as `max_requests_per_minute` that sit below the
    workspace's own plan limits so one project cannot consume the whole
    allowance, and it may be ARCHIVED, which suspends all work and spend
    inside it while everything stays readable.

    An application building on this platform models one of its OWN
    business customers as a project: it is the level that both
    attributes cost (`monthly_spend`, grouped per project on the usage
    breakdown) and ENFORCES it (`monthly_budget` and the capacity
    ceilings). How many projects a workspace may hold is the workspace's
    own ceiling; a create past it answers `409 project_limit_reached`,
    and deleting an unused project frees a slot.
    """

    archived_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the project was archived; `null` while it is live. While
    set, nothing new starts or bills inside the project and every
    such attempt answers `409 project_archived`.
    
    Absent rather than null while a console runs ahead of an API
    that predates archiving, which is why it is not required:
    read absent and null alike.
    """

    purged_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When this project was purged, present only on the rows returned
    by `include_purged=true`. A purged project is kept for 30 days
    from this stamp and permanently deleted after that, so the
    restore deadline is this value plus the window; it is absent on
    every project that still exists. Restore it with
    `POST /v1/projects/{project_id}/restore`.
    """

    max_requests_per_minute: typing.Optional[int] = pydantic.Field(default=None)
    """
    The most API requests per minute credentials pinned to this
    project may make across every surface, present only when set.
    Checked after the workspace's own request-rate limit, in one
    bucket per project: a request over the ceiling is refused with
    the same `429 rate_limited` the workspace limit answers, while
    other projects and unpinned credentials are untouched. Never
    higher than the workspace's widest per-surface rate over a
    minute: a project can narrow the workspace's capacity, not
    raise it. Console sessions and unpinned keys carry no project
    and are never subject to it.
    """

    monthly_budget: typing.Optional[float] = pydantic.Field(default=None)
    """
    The project's monthly spend limit in US dollars, present only
    when one is set. New billable work attributed to this project is
    refused with the coded `402 project_spend_limit_exceeded` once
    `monthly_spend` reaches it; the limit resets at the
    calendar-month boundary (UTC).
    
    Spend is attributed the same way it is billed: work from a
    project-pinned API key counts against that key's project, and
    work by a resource in a project counts against that project. The
    implicit Default project cannot carry a limit, since it has no
    project record, so spend there is bounded by the workspace's
    `monthly_budget` instead.
    """

    monthly_spend: typing.Optional[float] = pydantic.Field(default=None)
    """
    The project's billed month-to-date spend in US dollars, present
    whenever the billing plane answered - regardless of whether a
    spend limit is set.
    """

    monthly_budget_status: typing.Optional[ProjectMonthlyBudgetStatus] = pydantic.Field(default=None)
    """
    Where `monthly_spend` stands against `monthly_budget`, present
    only when both are: `warning` from 80% of the budget, `reached`
    once the spend has reached it and new billable work attributed to
    the project is refused with `402 project_spend_limit_exceeded`,
    `ok` below 80%. These are the thresholds the
    `project.spend_budget.warning` and `project.spend_budget.reached`
    webhook events fire at, so polling this field and subscribing to
    the events give the same answer.
    """

    monthly_budget_remaining: typing.Optional[float] = pydantic.Field(default=None)
    """
    `monthly_budget` minus `monthly_spend` in US dollars, present only
    when both are. Negative once the spend has passed the budget, by
    the amount it overshot: enforcement trails billed usage by a
    couple of minutes, so work already under way can carry a project
    past its budget.
    """

    id: str = pydantic.Field()
    """
    Workspace-scoped project identifier (prefixed external id).
    """

    name: str = pydantic.Field()
    """
    Human-readable label, unique per workspace (case-insensitive).
    """

    resource_count: int = pydantic.Field()
    """
    How many resources this project holds. Records of work that
    happened are not counted, and never hold a project open.
    
    It is the count the unqualified delete refuses on, so a project
    reading `0` is one `DELETE /v1/projects/{project_id}` accepts
    with no body. That is what makes an application's own cleanup a
    single list call rather than a read per project.
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
