# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .project_still_revoked_counts import ProjectStillRevokedCounts


class ProjectRestore(UniversalBaseModel):
    """
    The outcome of restoring a purged project: what deliberately did not
    come back.

    `still_revoked` counts the credentials the purge revoked and this
    call left revoked, because re-issuing a credential someone killed
    would hand back access rather than restore a project. Member grants
    and pending-invite scopes are in that group too, but their rows were
    removed by the purge, so they cannot be counted and appear only in
    `not_restored_note`.

    The project comes back ARCHIVED, the state it was purged from, so
    `archived_at` is always set: nothing dispatches or bills inside it
    until you unarchive it on purpose.
    """

    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    purged_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the purge this call walked back happened.
    """

    archived_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the project was archived. Always set on a restore: a project
    comes back suspended, never live.
    """

    still_revoked: typing.Optional[ProjectStillRevokedCounts] = None
    not_restored_note: typing.Optional[str] = pydantic.Field(default=None)
    """
    A plain-language statement of what a restore does not bring back.
    Constant text, meant to be shown to a person; branch on
    `still_revoked` rather than parsing it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
