# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .request_analytics_bucket import RequestAnalyticsBucket
from .request_analytics_totals import RequestAnalyticsTotals
from .request_top_path import RequestTopPath


class RequestAnalyticsResponse(UniversalBaseModel):
    """
    Aggregate request analytics over a window of the request log.
    """

    granularity: str = pydantic.Field()
    """
    The time-bucket size of the series.
    """

    start: dt.datetime = pydantic.Field()
    """
    Inclusive start of the resolved window.
    """

    end: dt.datetime = pydantic.Field()
    """
    Exclusive end of the resolved window.
    """

    totals: RequestAnalyticsTotals
    series: typing.List[RequestAnalyticsBucket] = pydantic.Field()
    """
    Per-bucket time series, oldest first.
    """

    top_paths: typing.List[RequestTopPath] = pydantic.Field()
    """
    The most-called route patterns in the window, busiest first.
    """

    project_filter_truncated: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True when a `project_id` filter's pinned key set exceeded the cap this endpoint applies: the result reflects only the project's newest keys within the cap, not its full traffic. Omitted (false) when no project filter was requested or its key set fit under the cap.
    """

    history_starts_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Hosted API analytics only: the first request in the last 30 days the request log attributes to this API. Requests before it cannot be attributed, so a bucket before it is missing data rather than zero traffic. Absent when no such request exists, in which case no bucket is known to be complete.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
