# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SpeechDoneEvent(UniversalBaseModel):
    """
    Terminal event: the synthesis completed and no further events follow.
    There is no `[DONE]` sentinel.
    """

    billable_characters_count: int = pydantic.Field()
    """
    Number of billable characters processed.
    """

    audio_duration_ms: int = pydantic.Field()
    """
    Duration of the synthesized audio in milliseconds.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
