# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .nested_chunk import NestedChunk


class SpeechChunkEvent(UniversalBaseModel):
    """
    A run of synthesized audio, the speech marks that became final with it,
    or both - a chunk may carry only one of the two, and the last chunk of
    a stream is often marks-only. Mark times are absolute milliseconds from
    the start of the synthesis: concatenate the audio chunks into one
    stream and apply the marks against that single timeline. Which chunk a
    mark arrives on is a delivery detail and carries no meaning.
    """

    audio: typing.Optional[str] = pydantic.Field(default=None)
    """
    A run of the synthesized audio, Base64-encoded, in the format the
    request selected (echoed on the `Speechify-Audio-Content-Type`
    response header). Absent on a marks-only chunk.
    """

    speech_marks: typing.Optional[typing.List[NestedChunk]] = pydantic.Field(default=None)
    """
    Word timings addressing the original input text, with absolute
    millisecond times from the start of the synthesis. Absent when the
    chunk carries only audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
