# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_detail import ErrorDetail
from .nested_chunk import NestedChunk


class SpeechStreamEvent_SpeechChunk(UniversalBaseModel):
    """
    One event on the POST /v1/audio/stream/with-timestamps stream. The
    `type` field discriminates the variants and mirrors the SSE `event:`
    name, so an event is identifiable from its `data:` payload alone.
    """

    type: typing.Literal["speech.chunk"] = "speech.chunk"
    audio: typing.Optional[str] = None
    speech_marks: typing.Optional[typing.List[NestedChunk]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SpeechStreamEvent_SpeechDone(UniversalBaseModel):
    """
    One event on the POST /v1/audio/stream/with-timestamps stream. The
    `type` field discriminates the variants and mirrors the SSE `event:`
    name, so an event is identifiable from its `data:` payload alone.
    """

    type: typing.Literal["speech.done"] = "speech.done"
    billable_characters_count: int
    audio_duration_ms: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SpeechStreamEvent_SpeechError(UniversalBaseModel):
    """
    One event on the POST /v1/audio/stream/with-timestamps stream. The
    `type` field discriminates the variants and mirrors the SSE `event:`
    name, so an event is identifiable from its `data:` payload alone.
    """

    type: typing.Literal["speech.error"] = "speech.error"
    error: ErrorDetail
    request_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


SpeechStreamEvent = typing_extensions.Annotated[
    typing.Union[SpeechStreamEvent_SpeechChunk, SpeechStreamEvent_SpeechDone, SpeechStreamEvent_SpeechError],
    pydantic.Field(discriminator="type"),
]
