# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WatermarkDetectionResponse(UniversalBaseModel):
    """
    The watermark detector's answer for one clip.

    `watermarked: true` is positive evidence the audio came from Speechify
    synthesis. `watermarked: false` is the absence of that evidence, not
    proof of a negative - see the endpoint description for the three reasons
    genuinely Speechify-generated audio can come back unmarked.
    """

    watermarked: bool = pydantic.Field()
    """
    Whether the clip carries the watermark, i.e. whether `confidence`
    cleared the service's configured bar.
    """

    confidence: float = pydantic.Field()
    """
    The detector's score for this clip, in [0, 1]. Comparable only
    between checks made against the same detector version.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
