# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WatermarkVerificationResponse(UniversalBaseModel):
    """
    The verification answer for one clip.

    One field, and no confidence score: a score is a gradient, and a public
    gradient turns "does this carry the mark" into "adjust the clip until
    the number drops". Use `POST /v1/audio/watermark/detect` if you need it.

    `watermarked: true` is positive evidence the audio came from Speechify
    synthesis. `watermarked: false` is the absence of that evidence, not
    proof of a negative - see the endpoint description.
    """

    watermarked: bool = pydantic.Field()
    """
    Whether the clip carries the Speechify watermark.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
