# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookEndpoint(UniversalBaseModel):
    """
    A workspace webhook endpoint: a destination URL, the events it
    subscribes to, and a server-minted HMAC signing secret. `secret` is
    returned ONLY in the create and rotate-secret responses — store it
    then; every other read omits it.

    An endpoint is either scoped to one project (`project_id`) or
    workspace-wide, and a workspace-wide endpoint receives events from
    every project.
    """

    id: str = pydantic.Field()
    """
    Prefixed wire id (`whe_<26 char Crockford base32>`).
    """

    url: str = pydantic.Field()
    """
    HTTPS destination Speechify POSTs signed events to.
    """

    project_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The project whose events this endpoint receives (prefixed
    external id). Null means workspace-wide - it receives every
    project's events. Endpoints have no Default project.
    
    An event is routed by the project frozen on the row that
    produced it (an API key's project, for example), and for a
    `project.spend_budget.*` event the project itself.
    Workspace-level events such as `workspace.spend_budget.*` belong
    to no project and reach workspace-wide endpoints only, so a
    scoped endpoint subscribed to those alone is refused with a 400
    naming `enabled_events` rather than accepted and never delivered
    to. A scoped endpoint records no delivery for another project's
    events.
    """

    enabled_events: typing.List[str] = pydantic.Field()
    """
    The events this endpoint receives: a list of catalog event names
    (for example `workspace.spend_budget.warning`) or `["*"]` for
    every event, current and future.
    """

    include: typing.List[str] = pydantic.Field()
    """
    Per-event payload shaping. Deliveries are lean by default:
    `data.object` carries only the resource GET snapshot. List heavy
    collections here to have them appended under the event's `data`
    alongside `object`, so receivers behind hard request-size caps
    stay lean unless they opt in. An event's documentation names the
    keys it recognises. Empty = lean.
    """

    api_version: dt.date = pydantic.Field()
    """
    The dated payload shape this endpoint receives (`YYYY-MM-DD`), the
    same versioning vocabulary the REST API uses. Every delivery is
    rendered back to this version and carries it in the
    `Speechify-Version` header and the payload's top-level `version`
    field. Defaults to your workspace's current version at creation;
    change it to opt into a newer shape.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional human-readable label for the endpoint.
    """

    disabled: bool = pydantic.Field()
    """
    When true, Speechify stops delivering to this endpoint.
    """

    secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    The HMAC-SHA256 signing secret (`whsec_…`) used to verify the
    `Speechify-Signature` header. Returned ONLY when the endpoint is
    created or its secret is rotated — it is never shown again.
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
