# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_delivery_status import WebhookDeliveryStatus


class WebhookEndpointDelivery(UniversalBaseModel):
    """
    One row of an endpoint's delivery log. One row per (endpoint, event,
    resource); updated in place across retry attempts. Each row records the
    exact request payload + signed headers Speechify sent and the response
    your server returned, so you can verify the signature and debug failures.
    """

    id: str = pydantic.Field()
    """
    Prefixed delivery id (`whd_<26 char Crockford base32>`).
    """

    webhook_endpoint_id: str = pydantic.Field()
    """
    The endpoint this delivery targeted (`whe_…`).
    """

    event: str = pydantic.Field()
    """
    The event type delivered (see `WebhookEventType`).
    """

    url: str = pydantic.Field()
    """
    The destination URL at delivery time.
    """

    status: WebhookDeliveryStatus
    attempt_count: int
    last_attempt_at: typing.Optional[dt.datetime] = None
    last_status_code: typing.Optional[int] = None
    last_error: typing.Optional[str] = None
    created_at: dt.datetime
    request_body: typing.Optional[str] = pydantic.Field(default=None)
    """
    The verbatim payload the `Speechify-Signature` HMAC was computed over
    (as `<t>.<raw_body>`).
    """

    request_headers: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Headers sent, including `Speechify-Signature` / `Speechify-Event` / `Speechify-Delivery-Id`.
    """

    last_response_body: typing.Optional[str] = pydantic.Field(default=None)
    """
    Your server's response body on the most recent attempt (truncated to 8 KiB).
    """

    last_response_headers: typing.Optional[typing.Dict[str, str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
