# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.list_webhook_endpoint_deliveries_response import ListWebhookEndpointDeliveriesResponse
from ...types.list_webhook_endpoints_response import ListWebhookEndpointsResponse
from ...types.webhook_endpoint import WebhookEndpoint
from ...types.webhook_endpoint_delivery import WebhookEndpointDelivery
from .raw_client import AsyncRawEndpointsClient, RawEndpointsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EndpointsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEndpointsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[WebhookEndpoint, ListWebhookEndpointsResponse]:
        """
        The caller's workspace's registered webhook endpoints. Cursor-paginated:
        omit `cursor` for the first page; walk pages while `has_more` is true
        (default page size 50, max 200). The signing `secret` is never returned
        here — it is shown only when an endpoint is created or its secret is
        rotated. Filter by delivery scope with `project_id`.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        project_id : typing.Optional[str]
            Filter endpoints by project scope: omit for everything the caller
            may see, pass the literal `shared` for workspace-wide endpoints
            only, or a `proj_...` id for endpoints scoped to that project.
            Endpoints have no Default project - a null `project_id` means
            workspace-wide, so the literal here is `shared`, never `default`.
            Returns 404 project_not_found for a malformed id and for any
            project outside your reach: a project-pinned API key or
            service-account key reaches only its pinned project, and a member
            holding project grants reaches only the granted projects. That 404
            is the same in every case and does not reveal whether such a
            project exists - outside your reach a project is answered as
            nonexistent, never as forbidden. `shared` is always inside your
            reach. Inside it, a well-formed id that matches nothing yields an
            empty page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[WebhookEndpoint, ListWebhookEndpointsResponse]
            The workspace's webhook endpoints.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        response = client.webhooks.endpoints.list(
            project_id="proj_01arz3ndektsv4rrffq69g5fav",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(cursor=cursor, limit=limit, project_id=project_id, request_options=request_options)

    def create(
        self,
        *,
        url: str,
        enabled_events: typing.Sequence[str],
        project_id: typing.Optional[str] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        api_version: typing.Optional[dt.date] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookEndpoint:
        """
        Register a webhook endpoint. Speechify mints an HMAC signing secret
        and returns it in the response `secret` field — exactly once. Store it
        then; subsequent reads omit it (rotate it with the rotate-secret action
        if lost). Select events via `enabled_events`: a list of catalog event
        names or `["*"]` for every event. Optionally scope delivery to one
        project with `project_id`; omit it for a workspace-wide endpoint that
        receives every project's events. Limited to 50 endpoints per workspace.

        Parameters
        ----------
        url : str
            HTTPS destination for event deliveries. Must be a publicly
            reachable host: loopback, private, link-local, and cloud-metadata
            addresses (and reserved hostnames like `localhost`) are rejected.

        enabled_events : typing.Sequence[str]
            Catalog event names to subscribe to, or `["*"]` for all events.

        project_id : typing.Optional[str]
            Optionally scope the endpoint to one project (prefixed
            `proj_...` id): a scoped endpoint receives only that project's
            events. Omit (or null) for workspace-wide - it receives every
            project's events. An unknown id returns 404 project_not_found.
            A project-pinned API key creates into its own project and
            cannot name the workspace-wide tier.

        include : typing.Optional[typing.Sequence[str]]
            Optional payload-shaping keys (see `WebhookEndpoint.include`).
            Omit for the lean default.

        api_version : typing.Optional[dt.date]
            Optionally pin the endpoint's payload shape to a dated version
            (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to use the
            workspace's current version. An unknown version is rejected.

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            The created endpoint, including its one-time signing secret.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.webhooks.endpoints.create(
            url="https://example.com/speechify/webhooks",
            enabled_events=["project.spend_budget.warning"],
            description="Example description.",
        )
        """
        _response = self._raw_client.create(
            url=url,
            enabled_events=enabled_events,
            project_id=project_id,
            include=include,
            api_version=api_version,
            description=description,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookEndpoint:
        """
        Fetch a webhook endpoint by id. The signing secret is never returned.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            The webhook endpoint (without the signing secret).

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.webhooks.endpoints.get(
            webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.get(webhook_endpoint_id, request_options=request_options)
        return _response.data

    def delete(self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a webhook endpoint. In-flight deliveries stop; returns 204 on success.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.webhooks.endpoints.delete(
            webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.delete(webhook_endpoint_id, request_options=request_options)
        return _response.data

    def update(
        self,
        webhook_endpoint_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        enabled_events: typing.Optional[typing.Sequence[str]] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        api_version: typing.Optional[dt.date] = OMIT,
        description: typing.Optional[str] = OMIT,
        disabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookEndpoint:
        """
        Partial update; omitted fields are left unchanged. Set `disabled` to pause delivery without deleting the endpoint.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        url : typing.Optional[str]
            HTTPS destination for event deliveries. Must be a publicly
            reachable host: loopback, private, link-local, and cloud-metadata
            addresses (and reserved hostnames like `localhost`) are rejected.

        project_id : typing.Optional[str]
            Re-scope the endpoint: a `proj_...` id narrows it to that
            project's events, an explicit null makes it workspace-wide
            (every project's events), omitted leaves it unchanged. The
            signing secret and delivery history are untouched, so
            re-scoping never requires redeploying your receiver. An
            unknown id returns 404 project_not_found. A project-pinned API
            key may only scope an endpoint to its own project.

        enabled_events : typing.Optional[typing.Sequence[str]]

        include : typing.Optional[typing.Sequence[str]]
            Payload-shaping keys (see `WebhookEndpoint.include`). Send `[]` to
            clear back to the lean default.

        api_version : typing.Optional[dt.date]
            Opt the endpoint into a different (typically newer) payload shape
            (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to leave it
            unchanged. An unknown version is rejected.

        description : typing.Optional[str]

        disabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            The updated endpoint (without the signing secret).

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.webhooks.endpoints.update(
            webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
            url="https://example.com/webhook",
            enabled_events=["example"],
            description="Example description.",
            disabled=False,
        )
        """
        _response = self._raw_client.update(
            webhook_endpoint_id,
            url=url,
            project_id=project_id,
            enabled_events=enabled_events,
            include=include,
            api_version=api_version,
            description=description,
            disabled=disabled,
            request_options=request_options,
        )
        return _response.data

    def rotate_secret(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookEndpoint:
        """
        Mint a new HMAC signing secret for the endpoint and return it in the
        response `secret` field (shown exactly once). The previous secret stops
        signing immediately, so accept both during your cutover window.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            The endpoint, including its new one-time signing secret.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.webhooks.endpoints.rotate_secret(
            webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        """
        _response = self._raw_client.rotate_secret(webhook_endpoint_id, request_options=request_options)
        return _response.data

    def list_deliveries(
        self,
        webhook_endpoint_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[WebhookEndpointDelivery, ListWebhookEndpointDeliveriesResponse]:
        """
        Delivery attempts for one webhook endpoint, newest first. One row per
        (endpoint, event, resource), updated in place across retries. Each row
        includes the exact request payload and signed headers Speechify sent
        (`request_body`, `request_headers`) and the response your server returned
        (`last_status_code`, `last_response_body`, `last_response_headers`), so
        you can verify the signature and debug failures. Cursor-paginated: omit
        `cursor` for the first page; walk pages while `has_more` is true (default
        page size 50, max 200).

        An endpoint that was not a target of an event has no row for it: a
        project-scoped endpoint records nothing for another project's events.
        An empty list therefore means either nothing matched or nothing
        happened. To tell them apart, check the project's own activity first:
        activity there with no delivery here is a defect to report; none there
        means there was nothing to deliver.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[WebhookEndpointDelivery, ListWebhookEndpointDeliveriesResponse]
            The endpoint's delivery attempts.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        response = client.webhooks.endpoints.list_deliveries(
            webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_deliveries(
            webhook_endpoint_id, cursor=cursor, limit=limit, request_options=request_options
        )


class AsyncEndpointsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEndpointsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[WebhookEndpoint, ListWebhookEndpointsResponse]:
        """
        The caller's workspace's registered webhook endpoints. Cursor-paginated:
        omit `cursor` for the first page; walk pages while `has_more` is true
        (default page size 50, max 200). The signing `secret` is never returned
        here — it is shown only when an endpoint is created or its secret is
        rotated. Filter by delivery scope with `project_id`.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        project_id : typing.Optional[str]
            Filter endpoints by project scope: omit for everything the caller
            may see, pass the literal `shared` for workspace-wide endpoints
            only, or a `proj_...` id for endpoints scoped to that project.
            Endpoints have no Default project - a null `project_id` means
            workspace-wide, so the literal here is `shared`, never `default`.
            Returns 404 project_not_found for a malformed id and for any
            project outside your reach: a project-pinned API key or
            service-account key reaches only its pinned project, and a member
            holding project grants reaches only the granted projects. That 404
            is the same in every case and does not reveal whether such a
            project exists - outside your reach a project is answered as
            nonexistent, never as forbidden. `shared` is always inside your
            reach. Inside it, a well-formed id that matches nothing yields an
            empty page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[WebhookEndpoint, ListWebhookEndpointsResponse]
            The workspace's webhook endpoints.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.webhooks.endpoints.list(
                project_id="proj_01arz3ndektsv4rrffq69g5fav",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            cursor=cursor, limit=limit, project_id=project_id, request_options=request_options
        )

    async def create(
        self,
        *,
        url: str,
        enabled_events: typing.Sequence[str],
        project_id: typing.Optional[str] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        api_version: typing.Optional[dt.date] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookEndpoint:
        """
        Register a webhook endpoint. Speechify mints an HMAC signing secret
        and returns it in the response `secret` field — exactly once. Store it
        then; subsequent reads omit it (rotate it with the rotate-secret action
        if lost). Select events via `enabled_events`: a list of catalog event
        names or `["*"]` for every event. Optionally scope delivery to one
        project with `project_id`; omit it for a workspace-wide endpoint that
        receives every project's events. Limited to 50 endpoints per workspace.

        Parameters
        ----------
        url : str
            HTTPS destination for event deliveries. Must be a publicly
            reachable host: loopback, private, link-local, and cloud-metadata
            addresses (and reserved hostnames like `localhost`) are rejected.

        enabled_events : typing.Sequence[str]
            Catalog event names to subscribe to, or `["*"]` for all events.

        project_id : typing.Optional[str]
            Optionally scope the endpoint to one project (prefixed
            `proj_...` id): a scoped endpoint receives only that project's
            events. Omit (or null) for workspace-wide - it receives every
            project's events. An unknown id returns 404 project_not_found.
            A project-pinned API key creates into its own project and
            cannot name the workspace-wide tier.

        include : typing.Optional[typing.Sequence[str]]
            Optional payload-shaping keys (see `WebhookEndpoint.include`).
            Omit for the lean default.

        api_version : typing.Optional[dt.date]
            Optionally pin the endpoint's payload shape to a dated version
            (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to use the
            workspace's current version. An unknown version is rejected.

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            The created endpoint, including its one-time signing secret.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.endpoints.create(
                url="https://example.com/speechify/webhooks",
                enabled_events=["project.spend_budget.warning"],
                description="Example description.",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            url=url,
            enabled_events=enabled_events,
            project_id=project_id,
            include=include,
            api_version=api_version,
            description=description,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookEndpoint:
        """
        Fetch a webhook endpoint by id. The signing secret is never returned.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            The webhook endpoint (without the signing secret).

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.endpoints.get(
                webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(webhook_endpoint_id, request_options=request_options)
        return _response.data

    async def delete(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete a webhook endpoint. In-flight deliveries stop; returns 204 on success.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.endpoints.delete(
                webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(webhook_endpoint_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        webhook_endpoint_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        enabled_events: typing.Optional[typing.Sequence[str]] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        api_version: typing.Optional[dt.date] = OMIT,
        description: typing.Optional[str] = OMIT,
        disabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookEndpoint:
        """
        Partial update; omitted fields are left unchanged. Set `disabled` to pause delivery without deleting the endpoint.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        url : typing.Optional[str]
            HTTPS destination for event deliveries. Must be a publicly
            reachable host: loopback, private, link-local, and cloud-metadata
            addresses (and reserved hostnames like `localhost`) are rejected.

        project_id : typing.Optional[str]
            Re-scope the endpoint: a `proj_...` id narrows it to that
            project's events, an explicit null makes it workspace-wide
            (every project's events), omitted leaves it unchanged. The
            signing secret and delivery history are untouched, so
            re-scoping never requires redeploying your receiver. An
            unknown id returns 404 project_not_found. A project-pinned API
            key may only scope an endpoint to its own project.

        enabled_events : typing.Optional[typing.Sequence[str]]

        include : typing.Optional[typing.Sequence[str]]
            Payload-shaping keys (see `WebhookEndpoint.include`). Send `[]` to
            clear back to the lean default.

        api_version : typing.Optional[dt.date]
            Opt the endpoint into a different (typically newer) payload shape
            (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to leave it
            unchanged. An unknown version is rejected.

        description : typing.Optional[str]

        disabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            The updated endpoint (without the signing secret).

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.endpoints.update(
                webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
                url="https://example.com/webhook",
                enabled_events=["example"],
                description="Example description.",
                disabled=False,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            webhook_endpoint_id,
            url=url,
            project_id=project_id,
            enabled_events=enabled_events,
            include=include,
            api_version=api_version,
            description=description,
            disabled=disabled,
            request_options=request_options,
        )
        return _response.data

    async def rotate_secret(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookEndpoint:
        """
        Mint a new HMAC signing secret for the endpoint and return it in the
        response `secret` field (shown exactly once). The previous secret stops
        signing immediately, so accept both during your cutover window.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            The endpoint, including its new one-time signing secret.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.endpoints.rotate_secret(
                webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_secret(webhook_endpoint_id, request_options=request_options)
        return _response.data

    async def list_deliveries(
        self,
        webhook_endpoint_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[WebhookEndpointDelivery, ListWebhookEndpointDeliveriesResponse]:
        """
        Delivery attempts for one webhook endpoint, newest first. One row per
        (endpoint, event, resource), updated in place across retries. Each row
        includes the exact request payload and signed headers Speechify sent
        (`request_body`, `request_headers`) and the response your server returned
        (`last_status_code`, `last_response_body`, `last_response_headers`), so
        you can verify the signature and debug failures. Cursor-paginated: omit
        `cursor` for the first page; walk pages while `has_more` is true (default
        page size 50, max 200).

        An endpoint that was not a target of an event has no row for it: a
        project-scoped endpoint records nothing for another project's events.
        An empty list therefore means either nothing matched or nothing
        happened. To tell them apart, check the project's own activity first:
        activity there with no delivery here is a defect to report; none there
        means there was nothing to deliver.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[WebhookEndpointDelivery, ListWebhookEndpointDeliveriesResponse]
            The endpoint's delivery attempts.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.webhooks.endpoints.list_deliveries(
                webhook_endpoint_id="whe_01jqr8x9zg5k2m3n4p5q6r7s8t",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_deliveries(
            webhook_endpoint_id, cursor=cursor, limit=limit, request_options=request_options
        )
