# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.jsonable_encoder import encode_path_param
from ...core.pagination import AsyncPager, SyncPager
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...errors.bad_request_error import BadRequestError
from ...errors.forbidden_error import ForbiddenError
from ...errors.internal_server_error import InternalServerError
from ...errors.not_found_error import NotFoundError
from ...errors.too_many_requests_error import TooManyRequestsError
from ...errors.unauthorized_error import UnauthorizedError
from ...errors.unprocessable_entity_error import UnprocessableEntityError
from ...types.error import Error
from ...types.list_webhook_endpoint_deliveries_response import ListWebhookEndpointDeliveriesResponse
from ...types.list_webhook_endpoints_response import ListWebhookEndpointsResponse
from ...types.webhook_endpoint import WebhookEndpoint
from ...types.webhook_endpoint_delivery import WebhookEndpointDelivery
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawEndpointsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[WebhookEndpoint, ListWebhookEndpointsResponse]:
        """
        The caller's workspace's registered webhook endpoints. Cursor-paginated:
        omit `cursor` for the first page; walk pages while `has_more` is true
        (default page size 50, max 200). The signing `secret` is never returned
        here — it is shown only when an endpoint is created or its secret is
        rotated. Filter by delivery scope with `project_id`.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        project_id : typing.Optional[str]
            Filter endpoints by project scope: omit for everything the caller
            may see, pass the literal `shared` for workspace-wide endpoints
            only, or a `proj_...` id for endpoints scoped to that project.
            Endpoints have no Default project - a null `project_id` means
            workspace-wide, so the literal here is `shared`, never `default`.
            Returns 404 project_not_found for a malformed id and for any
            project outside your reach: a project-pinned API key or
            service-account key reaches only its pinned project, and a member
            holding project grants reaches only the granted projects. That 404
            is the same in every case and does not reveal whether such a
            project exists - outside your reach a project is answered as
            nonexistent, never as forbidden. `shared` is always inside your
            reach. Inside it, a well-formed id that matches nothing yields an
            empty page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[WebhookEndpoint, ListWebhookEndpointsResponse]
            The workspace's webhook endpoints.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/webhooks/endpoints",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
                "project_id": project_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListWebhookEndpointsResponse,
                    parse_obj_as(
                        type_=ListWebhookEndpointsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.endpoints
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list(
                    cursor=_parsed_next,
                    limit=limit,
                    project_id=project_id,
                    request_options=request_options,
                )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        url: str,
        enabled_events: typing.Sequence[str],
        project_id: typing.Optional[str] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        api_version: typing.Optional[dt.date] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WebhookEndpoint]:
        """
        Register a webhook endpoint. Speechify mints an HMAC signing secret
        and returns it in the response `secret` field — exactly once. Store it
        then; subsequent reads omit it (rotate it with the rotate-secret action
        if lost). Select events via `enabled_events`: a list of catalog event
        names or `["*"]` for every event. Optionally scope delivery to one
        project with `project_id`; omit it for a workspace-wide endpoint that
        receives every project's events. Limited to 50 endpoints per workspace.

        Parameters
        ----------
        url : str
            HTTPS destination for event deliveries. Must be a publicly
            reachable host: loopback, private, link-local, and cloud-metadata
            addresses (and reserved hostnames like `localhost`) are rejected.

        enabled_events : typing.Sequence[str]
            Catalog event names to subscribe to, or `["*"]` for all events.

        project_id : typing.Optional[str]
            Optionally scope the endpoint to one project (prefixed
            `proj_...` id): a scoped endpoint receives only that project's
            events. Omit (or null) for workspace-wide - it receives every
            project's events. An unknown id returns 404 project_not_found.
            A project-pinned API key creates into its own project and
            cannot name the workspace-wide tier.

        include : typing.Optional[typing.Sequence[str]]
            Optional payload-shaping keys (see `WebhookEndpoint.include`).
            Omit for the lean default.

        api_version : typing.Optional[dt.date]
            Optionally pin the endpoint's payload shape to a dated version
            (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to use the
            workspace's current version. An unknown version is rejected.

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WebhookEndpoint]
            The created endpoint, including its one-time signing secret.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/webhooks/endpoints",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "url": url,
                "project_id": project_id,
                "enabled_events": enabled_events,
                "include": include,
                "api_version": api_version,
                "description": description,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookEndpoint,
                    parse_obj_as(
                        type_=WebhookEndpoint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WebhookEndpoint]:
        """
        Fetch a webhook endpoint by id. The signing secret is never returned.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WebhookEndpoint]
            The webhook endpoint (without the signing secret).
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookEndpoint,
                    parse_obj_as(
                        type_=WebhookEndpoint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Delete a webhook endpoint. In-flight deliveries stop; returns 204 on success.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        webhook_endpoint_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        enabled_events: typing.Optional[typing.Sequence[str]] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        api_version: typing.Optional[dt.date] = OMIT,
        description: typing.Optional[str] = OMIT,
        disabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WebhookEndpoint]:
        """
        Partial update; omitted fields are left unchanged. Set `disabled` to pause delivery without deleting the endpoint.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        url : typing.Optional[str]
            HTTPS destination for event deliveries. Must be a publicly
            reachable host: loopback, private, link-local, and cloud-metadata
            addresses (and reserved hostnames like `localhost`) are rejected.

        project_id : typing.Optional[str]
            Re-scope the endpoint: a `proj_...` id narrows it to that
            project's events, an explicit null makes it workspace-wide
            (every project's events), omitted leaves it unchanged. The
            signing secret and delivery history are untouched, so
            re-scoping never requires redeploying your receiver. An
            unknown id returns 404 project_not_found. A project-pinned API
            key may only scope an endpoint to its own project.

        enabled_events : typing.Optional[typing.Sequence[str]]

        include : typing.Optional[typing.Sequence[str]]
            Payload-shaping keys (see `WebhookEndpoint.include`). Send `[]` to
            clear back to the lean default.

        api_version : typing.Optional[dt.date]
            Opt the endpoint into a different (typically newer) payload shape
            (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to leave it
            unchanged. An unknown version is rejected.

        description : typing.Optional[str]

        disabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WebhookEndpoint]
            The updated endpoint (without the signing secret).
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="PATCH",
            json={
                "url": url,
                "project_id": project_id,
                "enabled_events": enabled_events,
                "include": include,
                "api_version": api_version,
                "description": description,
                "disabled": disabled,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookEndpoint,
                    parse_obj_as(
                        type_=WebhookEndpoint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def rotate_secret(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WebhookEndpoint]:
        """
        Mint a new HMAC signing secret for the endpoint and return it in the
        response `secret` field (shown exactly once). The previous secret stops
        signing immediately, so accept both during your cutover window.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WebhookEndpoint]
            The endpoint, including its new one-time signing secret.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}/rotate-secret",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookEndpoint,
                    parse_obj_as(
                        type_=WebhookEndpoint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_deliveries(
        self,
        webhook_endpoint_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[WebhookEndpointDelivery, ListWebhookEndpointDeliveriesResponse]:
        """
        Delivery attempts for one webhook endpoint, newest first. One row per
        (endpoint, event, resource), updated in place across retries. Each row
        includes the exact request payload and signed headers Speechify sent
        (`request_body`, `request_headers`) and the response your server returned
        (`last_status_code`, `last_response_body`, `last_response_headers`), so
        you can verify the signature and debug failures. Cursor-paginated: omit
        `cursor` for the first page; walk pages while `has_more` is true (default
        page size 50, max 200).

        An endpoint that was not a target of an event has no row for it: a
        project-scoped endpoint records nothing for another project's events.
        An empty list therefore means either nothing matched or nothing
        happened. To tell them apart, check the project's own activity first:
        activity there with no delivery here is a defect to report; none there
        means there was nothing to deliver.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[WebhookEndpointDelivery, ListWebhookEndpointDeliveriesResponse]
            The endpoint's delivery attempts.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}/deliveries",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListWebhookEndpointDeliveriesResponse,
                    parse_obj_as(
                        type_=ListWebhookEndpointDeliveriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.deliveries
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list_deliveries(
                    webhook_endpoint_id,
                    cursor=_parsed_next,
                    limit=limit,
                    request_options=request_options,
                )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawEndpointsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[WebhookEndpoint, ListWebhookEndpointsResponse]:
        """
        The caller's workspace's registered webhook endpoints. Cursor-paginated:
        omit `cursor` for the first page; walk pages while `has_more` is true
        (default page size 50, max 200). The signing `secret` is never returned
        here — it is shown only when an endpoint is created or its secret is
        rotated. Filter by delivery scope with `project_id`.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        project_id : typing.Optional[str]
            Filter endpoints by project scope: omit for everything the caller
            may see, pass the literal `shared` for workspace-wide endpoints
            only, or a `proj_...` id for endpoints scoped to that project.
            Endpoints have no Default project - a null `project_id` means
            workspace-wide, so the literal here is `shared`, never `default`.
            Returns 404 project_not_found for a malformed id and for any
            project outside your reach: a project-pinned API key or
            service-account key reaches only its pinned project, and a member
            holding project grants reaches only the granted projects. That 404
            is the same in every case and does not reveal whether such a
            project exists - outside your reach a project is answered as
            nonexistent, never as forbidden. `shared` is always inside your
            reach. Inside it, a well-formed id that matches nothing yields an
            empty page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[WebhookEndpoint, ListWebhookEndpointsResponse]
            The workspace's webhook endpoints.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/webhooks/endpoints",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
                "project_id": project_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListWebhookEndpointsResponse,
                    parse_obj_as(
                        type_=ListWebhookEndpointsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.endpoints
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""

                async def _get_next():
                    return await self.list(
                        cursor=_parsed_next,
                        limit=limit,
                        project_id=project_id,
                        request_options=request_options,
                    )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        url: str,
        enabled_events: typing.Sequence[str],
        project_id: typing.Optional[str] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        api_version: typing.Optional[dt.date] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WebhookEndpoint]:
        """
        Register a webhook endpoint. Speechify mints an HMAC signing secret
        and returns it in the response `secret` field — exactly once. Store it
        then; subsequent reads omit it (rotate it with the rotate-secret action
        if lost). Select events via `enabled_events`: a list of catalog event
        names or `["*"]` for every event. Optionally scope delivery to one
        project with `project_id`; omit it for a workspace-wide endpoint that
        receives every project's events. Limited to 50 endpoints per workspace.

        Parameters
        ----------
        url : str
            HTTPS destination for event deliveries. Must be a publicly
            reachable host: loopback, private, link-local, and cloud-metadata
            addresses (and reserved hostnames like `localhost`) are rejected.

        enabled_events : typing.Sequence[str]
            Catalog event names to subscribe to, or `["*"]` for all events.

        project_id : typing.Optional[str]
            Optionally scope the endpoint to one project (prefixed
            `proj_...` id): a scoped endpoint receives only that project's
            events. Omit (or null) for workspace-wide - it receives every
            project's events. An unknown id returns 404 project_not_found.
            A project-pinned API key creates into its own project and
            cannot name the workspace-wide tier.

        include : typing.Optional[typing.Sequence[str]]
            Optional payload-shaping keys (see `WebhookEndpoint.include`).
            Omit for the lean default.

        api_version : typing.Optional[dt.date]
            Optionally pin the endpoint's payload shape to a dated version
            (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to use the
            workspace's current version. An unknown version is rejected.

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WebhookEndpoint]
            The created endpoint, including its one-time signing secret.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/webhooks/endpoints",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "url": url,
                "project_id": project_id,
                "enabled_events": enabled_events,
                "include": include,
                "api_version": api_version,
                "description": description,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookEndpoint,
                    parse_obj_as(
                        type_=WebhookEndpoint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WebhookEndpoint]:
        """
        Fetch a webhook endpoint by id. The signing secret is never returned.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WebhookEndpoint]
            The webhook endpoint (without the signing secret).
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookEndpoint,
                    parse_obj_as(
                        type_=WebhookEndpoint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Delete a webhook endpoint. In-flight deliveries stop; returns 204 on success.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        webhook_endpoint_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        enabled_events: typing.Optional[typing.Sequence[str]] = OMIT,
        include: typing.Optional[typing.Sequence[str]] = OMIT,
        api_version: typing.Optional[dt.date] = OMIT,
        description: typing.Optional[str] = OMIT,
        disabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WebhookEndpoint]:
        """
        Partial update; omitted fields are left unchanged. Set `disabled` to pause delivery without deleting the endpoint.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        url : typing.Optional[str]
            HTTPS destination for event deliveries. Must be a publicly
            reachable host: loopback, private, link-local, and cloud-metadata
            addresses (and reserved hostnames like `localhost`) are rejected.

        project_id : typing.Optional[str]
            Re-scope the endpoint: a `proj_...` id narrows it to that
            project's events, an explicit null makes it workspace-wide
            (every project's events), omitted leaves it unchanged. The
            signing secret and delivery history are untouched, so
            re-scoping never requires redeploying your receiver. An
            unknown id returns 404 project_not_found. A project-pinned API
            key may only scope an endpoint to its own project.

        enabled_events : typing.Optional[typing.Sequence[str]]

        include : typing.Optional[typing.Sequence[str]]
            Payload-shaping keys (see `WebhookEndpoint.include`). Send `[]` to
            clear back to the lean default.

        api_version : typing.Optional[dt.date]
            Opt the endpoint into a different (typically newer) payload shape
            (`YYYY-MM-DD`, see `WebhookEndpoint.api_version`). Omit to leave it
            unchanged. An unknown version is rejected.

        description : typing.Optional[str]

        disabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WebhookEndpoint]
            The updated endpoint (without the signing secret).
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="PATCH",
            json={
                "url": url,
                "project_id": project_id,
                "enabled_events": enabled_events,
                "include": include,
                "api_version": api_version,
                "description": description,
                "disabled": disabled,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookEndpoint,
                    parse_obj_as(
                        type_=WebhookEndpoint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def rotate_secret(
        self, webhook_endpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WebhookEndpoint]:
        """
        Mint a new HMAC signing secret for the endpoint and return it in the
        response `secret` field (shown exactly once). The previous secret stops
        signing immediately, so accept both during your cutover window.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WebhookEndpoint]
            The endpoint, including its new one-time signing secret.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}/rotate-secret",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookEndpoint,
                    parse_obj_as(
                        type_=WebhookEndpoint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_deliveries(
        self,
        webhook_endpoint_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[WebhookEndpointDelivery, ListWebhookEndpointDeliveriesResponse]:
        """
        Delivery attempts for one webhook endpoint, newest first. One row per
        (endpoint, event, resource), updated in place across retries. Each row
        includes the exact request payload and signed headers Speechify sent
        (`request_body`, `request_headers`) and the response your server returned
        (`last_status_code`, `last_response_body`, `last_response_headers`), so
        you can verify the signature and debug failures. Cursor-paginated: omit
        `cursor` for the first page; walk pages while `has_more` is true (default
        page size 50, max 200).

        An endpoint that was not a target of an event has no row for it: a
        project-scoped endpoint records nothing for another project's events.
        An empty list therefore means either nothing matched or nothing
        happened. To tell them apart, check the project's own activity first:
        activity there with no delivery here is a defect to report; none there
        means there was nothing to deliver.

        Parameters
        ----------
        webhook_endpoint_id : str
            Webhook endpoint id (prefixed `whe_…`).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response.

        limit : typing.Optional[int]
            Max items per page (default 50, max 200).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[WebhookEndpointDelivery, ListWebhookEndpointDeliveriesResponse]
            The endpoint's delivery attempts.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/webhooks/endpoints/{encode_path_param(webhook_endpoint_id)}/deliveries",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListWebhookEndpointDeliveriesResponse,
                    parse_obj_as(
                        type_=ListWebhookEndpointDeliveriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.deliveries
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""

                async def _get_next():
                    return await self.list_deliveries(
                        webhook_endpoint_id,
                        cursor=_parsed_next,
                        limit=limit,
                        request_options=request_options,
                    )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
