# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.entitlements_response import EntitlementsResponse
from .raw_client import AsyncRawWorkspacesClient, RawWorkspacesClient


class WorkspacesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkspacesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkspacesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkspacesClient
        """
        return self._raw_client

    def get_entitlements(self, *, request_options: typing.Optional[RequestOptions] = None) -> EntitlementsResponse:
        """
        The per-tier entitlements catalog plus the caller's RESOLVED
        entitlements for the current workspace (tier defaults composed with
        any per-tenant override). Readable with an API key as well as a
        console session: it is how an integration learns what it may use
        before a feature endpoint answers `402`. Branch on
        `current.voice_cloning` and `current.hosted_apis_access`, and size
        traffic from
        `current.tts_requests_per_second` and `current.tts_concurrency`. The
        console renders quota affordances and upgrade-card limits from the
        same single server-authoritative source instead of a hardcoded
        mirror.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntitlementsResponse
            The entitlements catalog + the current workspace's resolved entitlements.

        Examples
        --------
        from speechify import Speechify

        client = Speechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )
        client.workspaces.get_entitlements()
        """
        _response = self._raw_client.get_entitlements(request_options=request_options)
        return _response.data


class AsyncWorkspacesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkspacesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkspacesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkspacesClient
        """
        return self._raw_client

    async def get_entitlements(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EntitlementsResponse:
        """
        The per-tier entitlements catalog plus the caller's RESOLVED
        entitlements for the current workspace (tier defaults composed with
        any per-tenant override). Readable with an API key as well as a
        console session: it is how an integration learns what it may use
        before a feature endpoint answers `402`. Branch on
        `current.voice_cloning` and `current.hosted_apis_access`, and size
        traffic from
        `current.tts_requests_per_second` and `current.tts_concurrency`. The
        console renders quota affordances and upgrade-card limits from the
        same single server-authoritative source instead of a hardcoded
        mirror.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntitlementsResponse
            The entitlements catalog + the current workspace's resolved entitlements.

        Examples
        --------
        import asyncio

        from speechify import AsyncSpeechify

        client = AsyncSpeechify(
            "2026-09-30",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.get_entitlements()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_entitlements(request_options=request_options)
        return _response.data
