# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.internal_server_error import InternalServerError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.entitlements_response import EntitlementsResponse
from ..types.error import Error
from pydantic import ValidationError


class RawWorkspacesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_entitlements(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EntitlementsResponse]:
        """
        The per-tier entitlements catalog plus the caller's RESOLVED
        entitlements for the current workspace (tier defaults composed with
        any per-tenant override). Readable with an API key as well as a
        console session: it is how an integration learns what it may use
        before a feature endpoint answers `402`. Branch on
        `current.voice_cloning`, `current.hosted_apis_access` and
        `current.waymark_access`, and size traffic from
        `current.tts_requests_per_second` and `current.tts_concurrency`. The
        console renders quota affordances and upgrade-card limits from the
        same single server-authoritative source instead of a hardcoded
        mirror.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EntitlementsResponse]
            The entitlements catalog + the current workspace's resolved entitlements.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workspaces/current/entitlements",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EntitlementsResponse,
                    parse_obj_as(
                        type_=EntitlementsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWorkspacesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_entitlements(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EntitlementsResponse]:
        """
        The per-tier entitlements catalog plus the caller's RESOLVED
        entitlements for the current workspace (tier defaults composed with
        any per-tenant override). Readable with an API key as well as a
        console session: it is how an integration learns what it may use
        before a feature endpoint answers `402`. Branch on
        `current.voice_cloning`, `current.hosted_apis_access` and
        `current.waymark_access`, and size traffic from
        `current.tts_requests_per_second` and `current.tts_concurrency`. The
        console renders quota affordances and upgrade-card limits from the
        same single server-authoritative source instead of a hardcoded
        mirror.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EntitlementsResponse]
            The entitlements catalog + the current workspace's resolved entitlements.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workspaces/current/entitlements",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EntitlementsResponse,
                    parse_obj_as(
                        type_=EntitlementsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
