# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient

if typing.TYPE_CHECKING:
    from .endpoints.client import AsyncEndpointsClient, EndpointsClient


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._endpoints: typing.Optional[EndpointsClient] = None

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    @property
    def endpoints(self):
        if self._endpoints is None:
            from .endpoints.client import EndpointsClient  # noqa: E402

            self._endpoints = EndpointsClient(client_wrapper=self._client_wrapper)
        return self._endpoints


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._endpoints: typing.Optional[AsyncEndpointsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    @property
    def endpoints(self):
        if self._endpoints is None:
            from .endpoints.client import AsyncEndpointsClient  # noqa: E402

            self._endpoints = AsyncEndpointsClient(client_wrapper=self._client_wrapper)
        return self._endpoints
